### ISSUE TITLE
clipboard.service.ts is missing from the TypeScript compilation.

### ISSUE THREAD

**Issue by fxck** [maxisam/ngx-clipboard#105]
> Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).

angular-cli 1.7.0-beta.0, ts 2.6.2

**Comment by dbusacca** [comment]
A temporary work-around is use
`import { ClipboardModule } from 'ngx-clipboard/dist';`
instead of
`import { ClipboardModule } from 'ngx-clipboard;`

**Comment by achimha** [comment]
angular-cli 1.6.5 now officially suports TypeScript 2.6.2 which triggers this error.

**Comment by maxisam** [comment]
Close this to track in #100
