### ISSUE TITLE
ng build --prod   ERROR in : Cannot determine the module for class TestClipboardComponent in 

### ISSUE THREAD

**Issue by jendy2012** [maxisam/ngx-clipboard#106]
ng build --prod

ERROR in : Cannot determine the module for class TestClipboardComponent in /Users/www1/node_modules/ngx-clipboard/src/clipboard.directive.spec.ts! Add TestClipboardComponent to the NgModule to fix it.

**Comment by maarten-vandevelde** [comment]
this is a side effect from the fact that the source .ts files are in the distributed package. The src folder should not be in the package published on the npm repo.

**Comment by maxisam** [comment]
close this and track it in #105.
