### ISSUE TITLE
Copy contents of <code> element

### ISSUE THREAD

**Issue by jainmitesh09** [maxisam/ngx-clipboard#107]
Hi,

I tried to use the plunkr to test the code element but it does not seem to work.

Is there an example that i can refer?

Thank you.

**Comment by jainmitesh09** [comment]
http://embed.plnkr.co/PD4Ap8/

**Comment by maxisam** [comment]
It seems working fine to me. Please ask support type of question on Stackoverflow. Thanks!

**Comment by jainmitesh09** [comment]
@maxisam I forked your plunker and made the changes to use a `<code>` element.

I used both the methods for the usage. 

Below is the plunker link.

https://embed.plnkr.co/3KJAAj1nVj3ydufXB7SL/

Can you please confirm it this works fine for you as well?

**Comment by maxisam** [comment]
No, it doesn't work. I don't think you can use ngModel like this. You
should ask this on Stackoverflow, since it is a general Angular question.
