### ISSUE TITLE
Angular 5.2: "fullTemplateTypeCheck": true leads to Error Message

### ISSUE THREAD

**Issue by DanielHabenicht** [maxisam/ngx-clipboard#108]
With the introduction of the Angular 5.2 `fullTemplateTypeCheck` Compiler Option an Error is thrown, when using ngx-clipboard: 
**Directive ClipboardDirective, Expected 0 arguments, but got 1.**

The Problem lies within clipboard.directive.ts `onClick()` Function, which specifies no arguments.

**Comment by maxisam** [comment]
I see. thx

**Comment by achimha** [comment]
Working now. Thank you.
