### ISSUE TITLE
RXJS related error TS2415

### ISSUE THREAD

**Issue by joshnickleby** [maxisam/ngx-clipboard#114]
typescript: ~2.5.3
rxjs: ^5.5.6

After npm install and subsequent ng serve it throws up the following error:

    ERROR in node_modules/angular2-clipboard/node_modules/rxjs/Subject.d.ts(16,22): error TS2415: 
        Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
        Types of property 'lift' are incompatible.
        Type '<R>(operator: Operator<T, R>) => 
            Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
        Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.

**Comment by maxisam** [comment]
please try v11.1.0
