### ISSUE TITLE
Should be able to target div/pre/span

### ISSUE THREAD

**Issue by seanmcilvenna** [maxisam/ngx-clipboard#115]
I would like to be able to target the contents of a DIV/SPAN/PRE element. I use pre element to display JSON, and would like to be able to copy the JSON it represents to the clipboard.

**Comment by seanmcilvenna** [comment]
I discovered how to do this with [cbContent]
My change request, instead, is that it automatically detect non-input fields that are the "target", and get the text value of the target and treating it like [cbContent].

**Comment by maxisam** [comment]
it is a nice idea. Welcome to make a PR.
