### ISSUE TITLE
Error during "ng build --prod"

### ISSUE THREAD

**Issue by DavidVotrubec** [maxisam/ngx-clipboard#117]
Steps to reproduce:

1) install ngx-clipboard via yarn/npm into your project
2) build via ng build --prod
3) boom

**the error basically says:**
Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv)

**Additional** notes:
I am using 
"angular/cli": "1.6.3",
"angular/compiler-cli": "^5.1.0",

**Full error:**

> ERROR in ./node_modules/ngx-clipboard/src/clipboard.directive.ts
> Module build failed: Error: C:\src\Nakamotox\apps\client\node_modules\ngx-clipboard\src\clipboard.directive.ts is missing from the TypeScript
> compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
>     at AngularCompilerPlugin.getCompiledFile (C:\src\___app_name___\apps\client\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:653:23)
>     at plugin.done.then (C:\src\___app_name___\apps\client\node_modules\@ngtools\webpack\src\loader.js:467:39)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
>  @ ./src/app/+stock/deposit-withdraw/popup-deposit/popup-deposit.component.ngfactory.js 21:0-61
>  @ ./src/app/+stock/dashboard/dashboard-bottom/dashboard-bottom.component.ngfactory.js
>  @ ./src/app/+stock/dashboard/dashboard.component.ngfactory.js
>  @ ./src/app/+stock/stock.module.ngfactory.js
>  @ ./src/$$_lazy_route_resource lazy
>  @ ./node_modules/@angular/core/esm5/core.js
>  @ ./src/main.ts
>  @ multi ./src/main.ts
> ERROR in ./node_modules/ngx-clipboard/src/clipboard.service.ts

**Comment by zralock** [comment]
+1

**Comment by maxisam** [comment]
what's the version of ngx-clipboard?

**Comment by maxisam** [comment]
no response. close for now,
