### ISSUE TITLE
Module build failed (version 10.0)

### ISSUE THREAD

**Issue by rbryan21** [maxisam/ngx-clipboard#119]
Hello, I am receiving this error when starting my application using the newest release of ngx-clipboard (10.0.0):

  `ERROR in ./node_modules/ngx-clipboard/src/clipboard.service.ts
Module build failed: Error: /node_modules/ngx-clipboard/src/clipboard.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:656:23)
    at plugin.done.then (/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

My angular version is 5.2.5.

Any help would be appreciated, thanks!

**Comment by maxisam** [comment]
because it is the way it should be. Please ask this on Stackoverflow to get more help.
