### ISSUE TITLE
Target should be input or textarea

### ISSUE THREAD

**Issue by AndreasSchmid1** [maxisam/ngx-clipboard#120]
No matter what I do. [ngxClipboard]="propertyLink" throws a "Error: Target should be input or textarea"

**Comment by maxisam** [comment]
please check with the example and ask support questions on Stackoverflow. Thanks!

**Comment by EduardsE** [comment]
Why couldn't you just help here? I also run into the same issue.

**Comment by maxisam** [comment]
@EduardsE Sorry, I happened to have a real job.

**Comment by EduardsE** [comment]
@maxisam Yeah, we all do, smartass.

**Comment by antonpegov** [comment]
Where is your example, dear author? Plank is not working!

**Comment by maxisam** [comment]
@antonpegov 
https://github.com/maxisam/ngx-clipboard/tree/master/demo/angularCli

**Comment by isherwood** [comment]
I have the same issue. I don't have an example, but here's my markup for reference. 

```
             <form [formGroup]="shareForm">
                <mat-form-field class="max-width">
                    <input matInput formControlName="shareUrl" placeholder="Click to copy URL" readonly="true" [cbContent]="currentUrl" (cbOnSuccess)="onClipboardCopy()">
                </mat-form-field>
            </form>
```

**Comment by maxisam** [comment]
Please ask general questions on StackOverflow. Thx

**Comment by isherwood** [comment]
I got it working by using both directives. The docs should be updated. 

`<input matInput formControlName="shareUrl" placeholder="Click to copy URL" readonly="true" ngxClipboard [cbContent]="currentUrl" (cbOnSuccess)="onClipboardCopy()">`
