### ISSUE TITLE
AngularJS/front/node_modules/ngx-clipboard/dist/src/clipboard.service.d.ts, found version 4, expected 3

### ISSUE THREAD

**Issue by Gajendrasinh** [maxisam/ngx-clipboard#121]
Hi

I am using angular 4, in Angular 4  which version work ngx-clipboard 

ERROR in Metadata version mismatch for module /Volumes/DATA/Projects/Tropitoken-AngularJS/front/node_modules/ngx-clipboard/dist/src/clipboard.service.d.ts, found version 4, expected 3

version details

"dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/material": "2.0.0-beta.2",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/platform-server": "4.4.6",
    "@angular/router": "4.4.6",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-beta.6",
    "angular2-cool-storage": "3.1.0",
    "angular2-toaster": "4.0.1",
    "bootstrap": "3.3.7",
    "chart.js": "2.4.0",
    "chart.piecelabel.js": "^0.9.0",
    "core-js": "2.4.1",
    "enhanced-resolve": "3.3.0",
    "font-awesome": "4.7.0",
    "jquery": "3.2.1",
    "moment": "^2.20.1",
    "ng2-google-charts": "^2.2.0",
    "ngx-bootstrap": "^2.0.2",
    "ngx-clipboard": "^9.1.3",
    "ngx-cookie-service": "1.0.9",
    "ngx-progressbar": "^2.1.1",
    "path": "^0.12.7",
    "rxjs": "5.3.0",
    "zone.js": "0.8.5"
  },

**Comment by maxisam** [comment]
I think you can find it from git history.
