### ISSUE TITLE
Unexpected token import (Angular Universal)

### ISSUE THREAD

**Issue by Supamiu** [maxisam/ngx-clipboard#124]
When trying to build for ssr (commonjs, as it needs to be used by nodejs), the build fails with the message above, aot and jit builds are working fine, just the universal build doesn't.

```
\node_modules\ngx-clipboard\dist\src\clipboard.directive.js:5
import { Directive, EventEmitter, HostListener, Input, Output } from "@angular/core";
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

### Workaround

I managed to make it work for now using this comment:
https://github.com/SebastianM/angular-google-maps/issues/1052#issuecomment-331150772

But the library should provide an Universal-compliant build in order to avoid letting the end developper do the job (which is basically transpiling the library using babel).

Same problem with ngx-window-token, I can duplicate the issue to it's repo if it's needed.

**Comment by Supamiu** [comment]
I did exactly the same thing with ngx-window-token and got no issues, I think this might be because you're using ngx-window-token outside of a frontend application (I don't see how tho) as window being undefined should only happen in this case (frontend applicaiton started in nodejs).

**Comment by maxisam** [comment]
@Supamiu is correct. You shouldn't even load ngx-clipboard for ssr. You can skip it and only load it when app starts.
