### ISSUE TITLE
not work under IE11

### ISSUE THREAD

**Issue by byunru** [maxisam/ngx-clipboard#125]
in polyfilles.ts, I turned on all import statements of  'core-js/es6/***';
and I also added =>  (window as any).__Zone_enable_cross_context_check = true; 
before line => import 'zone.js/dist/zone';

still not work, under IE 11 with error:
SCRIPT1002: Syntax error
vender.buncle.js

**Comment by MuruganLR** [comment]
Same Issue. It is not working in IE 11.431.16299.0

**Comment by maxisam** [comment]
try the v11.1.0, remember to uncomment all necessary polyfilles.

I just tested it and it works.
