### ISSUE TITLE
"export 'inject' was not found in '@angular/core'

### ISSUE THREAD

**Issue by ohabash** [maxisam/ngx-clipboard#132]
#in google console

```
Uncaught TypeError: Object(...) is not a function => ngx-clipboard.js:174 
```

#after `ng serve`
```
WARNING in ./node_modules/ngx-clipboard/fesm5/ngx-clipboard.js
174:152-158 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-clipboard/fesm5/ngx-clipboard.js
174:170-176 "export 'inject' was not found in '@angular/core'

WARNING in ./node_modules/ngx-clipboard/fesm5/ngx-clipboard.js
174:58-74 "export 'defineInjectable' was not found in '@angular/core'
```

if it wont work in ng5 you should say that in the docs before allowing people to waist hours trying to make it work.

**Comment by maxisam** [comment]
This is in the **Readme**

Angular >=6.0.0
If you need to use it on 2.x, please use version 7.x.x. If you need to use it on 4.x, please use version 8.x.x. If you need to use it on 5.x, please use version 10.x.x.

**Comment by ohabash** [comment]
I am using `"ngx-clipboard": "^11.1.0",`
