### ISSUE TITLE
Static Injector Error

### ISSUE THREAD

**Issue by hassanasad** [maxisam/ngx-clipboard#133]
Hi!

In the recent update of Ngx-clipboard (v11.1.0) along with Angular 6.0.2 i am getting the following error  inside the component template where i use `ngxClipboard [cbContent]="'somethingToCopy'"`:

```
Error: StaticInjectorError(AppModule)[ClipboardService -> InjectionToken WindowToken]: 
  StaticInjectorError(Platform: core)[ClipboardService -> InjectionToken WindowToken]: 
    NullInjectorError: No provider for InjectionToken WindowToken!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:979)
```

Any clues?
Perhaps something changed in Angular 6 related to staticInjectors ?

**Comment by maxisam** [comment]
You can clone this repo to local and run it. It works fine on my end. I think you might wanna try to upgrade your npm or use yarn.

**Comment by dbusacca** [comment]
I've got the same issue, It's module-related.
I've resolved adding either `NgxWindowTokenModule` or `ClipboardModule` to the root `AppModule`.

Previously I was using `ClipboardModule` only on a sub-module.
In Angular 5 it works, with Angular 6 it must added to the root module.

Maybe you should add a `ClipboardModule.forRoot()` function.

**Comment by hassanasad** [comment]
@dbusacca yeah thats what i was doing - i was loading it only in module i use the service. Moving it to root module does help get rid of the issue.

Its weird though why it would appear.

**Comment by achimha** [comment]
I can confirm the issue and the workaround. Anybody aware of the exact cause?

**Comment by hanvyj** [comment]
Same issue and workaround for me after upgrading from Angular 5 to 6.

**Comment by AnthonyNahas** [comment]
Im facing the same issue after updating angular to v6

**Comment by CharlBest** [comment]
This happened to me as well but with Angular Material specifically the OverlayModule. Placing it in the root module also fixed it temporarily but this is how they eventually fixed it so hope that helps. https://github.com/angular/material2/commit/0cda47c

**Comment by maxisam** [comment]
@CharlBest That is awesome. I think I know why.

**Comment by maxisam** [comment]
please try 11.1.1 Thanks!

**Comment by CharlBest** [comment]
Yes it works now. Thanks for the quick reply and fix.
