### ISSUE TITLE
Angular: Can't bind to 'cbContent' since it isn't a known property of 'button'. 

### ISSUE THREAD

**Issue by qq1209974887** [maxisam/ngx-clipboard#136]
Use Version:
angular@4.4.6
ngx-clipboard@8.1.4

![error](https://user-images.githubusercontent.com/18743063/40655754-f24f44c6-6374-11e8-8262-63bf60555afe.png)
![bwugym yq uk wvugy8j16](https://user-images.githubusercontent.com/18743063/40656130-0af8ae8a-6376-11e8-8235-9b691b89351e.png)
![l v nb d 14n7pkc9lm e](https://user-images.githubusercontent.com/18743063/40656131-0b5ea82a-6376-11e8-852c-4e8665ee1df9.png)

**Comment by qq1209974887** [comment]
angular4@4.4.6
ngx-clipboard@8.1.4

**Comment by maxisam** [comment]
Sorry, the version you used is kinda old. Please try to create a small demo code for your problem and ask it on Stackoverflow.
