### ISSUE TITLE
ng serve --prod fails for ngx-clipboard within a lazyloaded module

### ISSUE THREAD

**Issue by rahul0923** [maxisam/ngx-clipboard#138]
Hi,

Running ng serve --prod shows that issue. npm start is fine..

I am seeing an issue where ngx-clipboard version11.1.1 and angular cli 6.0.8 has issues in lazy loaded module
![ngx-clipboard issue](https://user-images.githubusercontent.com/19897523/41941637-71aa1722-7951-11e8-845f-9917756d3b4d.png)
![angular_version](https://user-images.githubusercontent.com/19897523/41941642-759efd66-7951-11e8-9a8e-6eb2ea01110a.png)

**Comment by freemanlam** [comment]
similar problem happened in lazy load module using JIT, message shown in browser console:
> core.js:1598 ERROR Error: Uncaught (in promise): Error: StaticInjectorError(AppModule)[ClipboardService -> InjectionToken WindowToken]: 
>   StaticInjectorError(Platform: core)[ClipboardService -> InjectionToken WindowToken]: 
>     NullInjectorError: No provider for InjectionToken WindowToken!
> Error: StaticInjectorError(AppModule)[ClipboardService -> InjectionToken WindowToken]: 
>   StaticInjectorError(Platform: core)[ClipboardService -> InjectionToken WindowToken]: 
>     NullInjectorError: No provider for InjectionToken WindowToken!

**Workaround:**
import ClipboardModule in CoreModule (or a not lazy module) directly

**Comment by maxisam** [comment]
I think #170  can fix this issue. try 12.0.0-beta.1

**Comment by maxisam** [comment]
no response, close for now.
