### ISSUE TITLE
[cbContent] doesn't accept functions (8.1.4)

### ISSUE THREAD

**Issue by mpetkov** [maxisam/ngx-clipboard#143]
I am using version 8.1.4 because I am currently running Angular 4. It looks like [cbContent] doesn't support passing functions. Is this intentional or a bug? If intentional, what is the reasoning?

These 2 work:
```
[cbContent]="'Text to Copy'"
[cbContent]="text"
```

This doesn't work:
`[cbContent]="getText()"`

At runtime, I get the following error:
**ERROR TypeError: Unexpected type object in select operator, expected 'string' or 'function'**

**Comment by maxisam** [comment]
It should work. You might wanna check your code. I suggest you create a online example to demo your issue and ask it on Stackoverflow. Thanks!
