### ISSUE TITLE
Text not copied while using a Clarity modal (a.k.a focus trapper issue)

### ISSUE THREAD

**Issue by digikar** [maxisam/ngx-clipboard#145]
I am using `[Clarity](https://vmware.github.io/clarity/documentation/v0.12/modals)` for my angular project. I tried using ngx-clipboard in an input element in a modal. But it does not seem to work. Whereas using it anywhere outside on modal on the same page seems to work seamlessly. This is a [stackblitz](https://stackblitz.com/edit/clarity-light-theme-v012-61srbw) to demonstrate my problem. Click the modal and enter a value to copy. It does not copy it to clipboard, whereas if i do the same thing outside the modal it works

**Comment by maxisam** [comment]
I think it has something to do with clarity's modal. However, I don't have time to investigate it now.  

I am sure it works with material's or bootstrap's  modal. I used it on Material's modal myself.

Anyway, this way it works. 
```
 <div class="modal-body">
         <input [(ngModel)]="text" #inputTarget>
      <button type="button" [ngxClipboard]="inputTarget">Copy</button>
  </div>
```

**Comment by omurbekjk** [comment]
@maxisam how can I add `textarea` to focus trapper or below the ngxClipboard directive?

**Comment by maxisam** [comment]
please try `ngx-clipboard@11.1.4-beta0`
