### ISSUE TITLE
(cbOnSuccess) triggered in IE11 when 'Don't Allow' access to clipboard is selected

### ISSUE THREAD

**Issue by bill-griffin** [maxisam/ngx-clipboard#147]
When using IE11, the user is prompted to allow the web page access to the clipboard. If they click 'Don't Allow', (cbOnSuccess) is triggered.
Using Angular 5 and ngx-clipboard v10.
Tried using both `[ngxClipboard]="textArea"` and `ngxClipboard [cbContent]="'text to copy'"` with the same result.

**Comment by maxisam** [comment]
It is a bug. I will try to address it soon. Welcome to submit a PR.

**Comment by maxisam** [comment]
please try v11.1.7 thx. Sorry about taking this one a bit longer.
