### ISSUE TITLE
Issue with unit tests (Jasmine)

### ISSUE THREAD

**Issue by ricardosobrado** [maxisam/ngx-clipboard#148]
Hi everyone!
I'm using version 10.0.0 of the ngx-clipboard (withAngular 5) and I'm facing some issues implementing unit tests with Jasmine! Note that it works perfectly just the unit tests are failing! 
The error I have is:
'StaticInjectorError(DynamicTestModule)[FragmentMenuComponent -> ClipboardService] 
It seems that it's not able to inject the service ClipboardService. I saw some previous answers that says that the ClipboardModule  needs to be added to AppModule. I tried to do this but didn't work for me!
The strange thing is the fact that only the unit tests are failing.
This is how I'm doing imports for the unit tests:
describe('FragmentMenuComponent', () => {
  let component: FragmentMenuComponent;
  let fixture: ComponentFixture<FragmentMenuComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        FragmentMenuComponent,
      ],
      imports: [
        WidgetsModule,
        HttpClientTestingModule,
        RouterTestingModule,
        ServicesModule,
        FragmentDefinitionModule,
        **ClipboardModule,**
      ],
      providers: [
        ToastNotificationService,
        BsModalService,
        TextFragmentEditService,
        OfficeFragmentEditService,
        FragmentEditService,
        Injector,
        ResetFragmentService,
        CertifyFragmentService,
        **ClipboardService,**
      ]
    })
    .compileComponents();
  }));  

Any ideas? Thank you in advance!

**Comment by maxisam** [comment]
Could you try the latest version?

**Comment by ricardosobrado** [comment]
Hi Maxisam!
I found the error! I have other unit tests, that are in other .spec files, that also import the component that is injecting the ClipboardService. What I had to do was go to all unit tests (spec.ts files) that import this component and add in providers the ClipboardService and in the imports the ClipboardModule. 
Thank you for your replay!

Kind regards,
Ricardo Magalhaes

**Comment by maxisam** [comment]
GJ! have a nice day.
