### ISSUE TITLE
if I use the [cbContent] in a modal, the document.body.appendChild(ta) will make the element can't select, please fix it.

### ISSUE THREAD

**Issue by yesterdaytime** [maxisam/ngx-clipboard#150]
https://github.com/maxisam/ngx-clipboard/blob/1d5a065a92a6df29d429bad35d62a26b616afb70/projects/ngx-clipboard/src/lib/ngx-clipboard.service.ts#L66
if the [cbContent]="value" is used in a modal, like the clarity's modal, It will add an element in the body,  because of the element and body is covered by the modal, it can't be selected.

**Comment by maxisam** [comment]
duplicated in #145 . Close this and track it there.

I wonder why both angular material modal and bootstrap modal work fine but not clarity's modal. I think what you said is possible, but I am kinda busy these couple weeks. You are welcome to make a pull request. Thanks!

**Comment by maxisam** [comment]
please try `ngx-clipboard@11.1.4-beta0`
