### ISSUE TITLE
Please consider components/elements with focus trapper

### ISSUE THREAD

**Issue by Shijir** [maxisam/ngx-clipboard#152]
Current implementation creates a <textarea> element, append it to the bottom of the document and select the <textarea> to copy its content. So this implementation won't work with any third-party component that incorporates a focus trapper. https://github.com/vmware/clarity/issues/2563. 

A possible solution could be to make that <textarea> off-screen and append it right below the ngxClipboard directive element. In that case, the <textarea> element would be still inside components or elements with focus trapper.

**Comment by maxisam** [comment]
That make total sense, welcome to make a pull request. Currently busy with work project.

**Comment by maxisam** [comment]
tracking this in #145.

**Comment by omurbekjk** [comment]
@maxisam @Shijir How can I append fake text area below `ngxClipboard` directive?
