### ISSUE TITLE
Can't bind to 'cbContent' since it isn't a known property of 'button'.

### ISSUE THREAD

**Issue by mpscheidt** [maxisam/ngx-clipboard#153]
Docu isn't correct.

Angular: 6.1.2
ngx-clipboard: 11.1.3

Docu says to use cbContent like this:
`<button [cbContent]="'target string'">Copy</button>`

which leads to this error:
`Can't bind to 'cbContent' since it isn't a known property of 'button'.`

Correct:
`<button ngxClipboard [cbContent]="'target string'">Copy</button>`

As can be seen in this [plunker ](https://embed.plnkr.co/PD4Ap8/)(app.component.html).

Please update docu.

**Comment by maxisam** [comment]
Good catch! Thank you!
