### ISSUE TITLE
can't use ClipboardService for copy

### ISSUE THREAD

**Issue by BennieMeng** [maxisam/ngx-clipboard#158]
i just want to use service to realize, but it can't work, see follow,
[stackblitz](https://stackblitz.com/edit/github-soo4k6?file=src/app/app.component.ts)

**Comment by maxisam** [comment]
Sorry about that. Please try 11.1.6. thx

**Comment by BennieMeng** [comment]
sorry , i change the version to  11.1.6, bug it also didn't work, please please me look for where is wrong.
[stackblitz](https://stackblitz.com/edit/github-soo4k6?file=src%2Fapp%2Fapp.component.ts)

**Comment by haengjin** [comment]
it also didn't work too.. (11.1.6)

**Comment by maxisam** [comment]
That's strange. I am working on it. Sorry about this.

**Comment by maxisam** [comment]
Interesting, I just add a demo in my repo, It does work. I think somehow stackblitz cache it? Checkout branch [hotfix/avoid-focus-trapper](https://github.com/maxisam/ngx-clipboard/tree/hotfix/avoid-focus-trapper), you will see it work on demo.
