### ISSUE TITLE
Error: Container should be a Dom element

### ISSUE THREAD

**Issue by mehmet2006** [maxisam/ngx-clipboard#159]
My code was working.
After the last update it started to give this error.

ERROR TypeError: Cannot read property 'contains' of undefined
    at ClipboardService.push../node_modules/ngx-clipboard/fesm5/ngx-clipboard.js.ClipboardService.copyFromContent (ngx-clipboard.js:81)

I am using clipboardService and my code is like:
this.clipboardService.copyFromContent(this.selectedGalleryItem.vimeoID)

Like I said it was working before the last update

Edit:
Just checked: 11.1.3 is working, 11.1.5 throws the above error

**Comment by maxisam** [comment]
sorry about that. Please try 11.1.6

**Comment by maxisam** [comment]
close this and track it at #158

**Comment by mehmet2006** [comment]
It is working. Thanks.
Great work by the way. Very easy to use...
