### ISSUE TITLE
call to this._clipboardService.copyFromContent(text) does not work

### ISSUE THREAD

**Issue by gigi199596** [maxisam/ngx-clipboard#164]
Hello,
I'm using Angular 4 with ngx-clipboard. Static copy to clipboard works but when I want it dynamic with a call to this._clipboardService.copyFromContent(text). It doesn't work.

I get this error:
`ERROR in /home/yolo/gestman/src/app/elicitation-form/results/results.component.ts (191,5): Supplied parameters do not match any signature of call target.`

Can someone help me?
Angular 4 v4.4.7, ngx-clipboard v8.1.4
Thanks a lot
Gilles

**Comment by solutweb** [comment]
I'm having a similar issue with `copyFromContent`.

I don't get any error but simply doesn't copy the string.

> Angular CLI: 6.2.6
> Node: 10.11.0
> OS: win32 x64
> Angular: 6.1.10
> -
> ngx-clipboard v11.1.9

**Comment by maxisam** [comment]
@solutweb have you try the demo site?

**Comment by solutweb** [comment]
> @solutweb have you try the demo site?

Yes and it worked. For now, I've changed the code logic to not use the service

**Comment by insanehong** [comment]
I have same problem too

**Comment by gigi199596** [comment]
I did a workaround guys. You should use a global variable...
`@Input() stringData: string = ""`

...in my case and preprocess the data string that is copied before the user clicks on the button:

`<button type="button" class="btn btn-success" ngxClipboard [cbContent]="stringData">Copy to clipboard</button>`

Hope it helps

**Comment by maxisam** [comment]
@insanehong could you build an example to show the problem?

**Comment by insanehong** [comment]
- **angular** 6.0.6
-  **ngx-clipboard** 11.1.9
- **zone.js** 0.8.26
- **webpack** 4.16.3
- **rxjs** 6.2.1

```js
import { ClipboardService } from 'ngx-clipboard'

...

constructor(private _clipboardService: ClipboardService){
...
}

copy(text: string){
  const copyResult = this._clipboardService.copyFromContent(text);
  console.log(copyResult)
}

// false
```

I think `document.execCommand("copy")` is not working in  angular.

**Comment by insanehong** [comment]
text copied that twice click to copy button used service

**Comment by maxisam** [comment]
@insanehong  did you try demo code? It works in demo.

**Comment by insanehong** [comment]
![ezgif-2-e3a9d7e10904](https://user-images.githubusercontent.com/1558742/48745806-3b69f880-ecb0-11e8-9ec5-f734d5b7f43a.gif)

**Comment by maxisam** [comment]
I would suggest you go to stackoverflow.

**Comment by gigi199596** [comment]
@maxisam thanks for your kind help

**Comment by maxisam** [comment]
for what it worth, I think there is a chance the new beta version,12.0.0-beta.1, might work.

**Comment by Hainesy** [comment]
Upgrading to 12.0.0-beta.1 does not fix the issue.

**Comment by Hainesy** [comment]
OK this is an issue with executing the copy command itself. It has to be done synchronously from a click command. Programmatically invoking a click invent on the hidden node should make the execCommand() work.
