### ISSUE TITLE
Modularize it to be able to compile with AoT

### ISSUE THREAD

**Issue by agustincelentano** [maxisam/ngx-clipboard#17]
It would be if it can be as a module in order to be able to compile it with AoT compilation mode. Actually it's a module but I am getting, Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.

I read your comment about changing to commonjs but I need to use es2015 in order to be able to compile using AoT

**Comment by maxisam** [comment]
I see. AoT is on my todo list. I will try it do it once I have time. PR is welcome as well.

**Comment by maxisam** [comment]
Please try the latest release, 2.0.5. I hope it will work. Thx

**Comment by maxisam** [comment]
I think 2.0.10 works with AoT. However, I can't get it build without error. But it still work, the error doesn't cause any problem.

**Comment by agustincelentano** [comment]
Not quite sure if I understood correctly. Can I add this as a module and is
it compatible to build it with AoT? Hadn't chance to try it out yet
Thanks

**Comment by maxisam** [comment]
sorry, it still doesn't work after more testing. I messed up previous test. It works in local not as a package.

**Comment by maxisam** [comment]
more specifically, I stuck with this error 

http://stackoverflow.com/questions/41307027/cannot-read-property-newline-of-undefined

Honestly, I feel like AoT is not ready for production. At least tools are not ready.

**Comment by agustincelentano** [comment]
Yes. it's super green. My angular app with uglifyjs is 1MB!. I tried to use
gzip but Amazon Elastic Beanstalk
<https://console.aws.amazon.com/elasticbeanstalk/home?region=us-east-1> does
not seem to support it. Don't know what to do to make my app size lesser

**Comment by maxisam** [comment]
without gzip, I don't think AoT is a good idea. The time on loading pretty much kills the time save from AoT.

**Comment by agustincelentano** [comment]
Justo un case, do you know an Amazon feature which supports gzip? It is
unusable

**Comment by maxisam** [comment]
sorry, i don't know.

**Comment by maxisam** [comment]
ok, 2.0.12 should work with AoT now. I just added an example code to demo to prove it.

**Comment by agustincelentano** [comment]
Ehy sam, I have changed the angular2-clipboard for the new name after
installing it. And checked if my app works as usual but I am getting this
strange error. I double check if the new module (ngx-clipboard) was the
cause and it is. Using it in my UrlsReleaseModule. Any ideas?
[image: Inline image 2]

**Comment by maxisam** [comment]
Ah. I don't see the image. But it should work. Check the demo code to see what is the difference.

**Comment by maxisam** [comment]
I also add a cli demo. I think it works.
