### ISSUE TITLE
no changelog?

### ISSUE THREAD

**Issue by nseni** [maxisam/ngx-clipboard#173]
Hello. In npm repository https://www.npmjs.com/package/ngx-clipboard the package was published 2 days ago. However there are no recent commits in master branch. What is going on?

**Comment by maxisam** [comment]
It was on pull request. For some reason, CI doesn't clear it, but it's
passed from CI. I thought Github might pass at some point.

**Comment by maxisam** [comment]
I just disabled the CI check and merge it. Something wrong with github and travis-ci.
