### ISSUE TITLE
A (little bit) more convenient way to use a global copy success message

### ISSUE THREAD

**Issue by smnbbrv** [maxisam/ngx-clipboard#174]
Hi @maxisam 

I'd love to set a global success event message that says that content was copied successfully.

Currently what I can do is

```ts
import { Injectable } from '@angular/core';
import { ClipboardService } from 'ngx-clipboard';
import { MessengerService } from './messenger/messenger.service';

@Injectable({
  providedIn: 'root',
})
export class ExtendedClipboardService extends ClipboardService {

  constructor(
    private messenger: MessengerService,
  ) {
    super(document, window);
  }

  public copyFromInputElement(targetElm: HTMLInputElement | HTMLTextAreaElement): boolean {
    const result = super.copyFromInputElement(targetElm);

    if (result) {
      this.messenger.messageSuccess('Copied to clipboard');
    } else {
      this.messenger.messageError('Cannot copy to clipboard');
    }

    return result;
  }

}

```

and then provide it in app.module.ts as 

```ts
{ provide: ClipboardService, useClass: ExtendedClipboardService },
```

Is there a better possibility to do that? Cause the current version is not based on a stable API and I am afraid it can stop working with next updates.

**Comment by smnbbrv** [comment]
and yep, the library is super! Thank you for your work!

**Comment by maxisam** [comment]
First of all, copyFromInputElement and copyFromContent are pretty stable APIs which is why I add `Public` to them to remind me they are public API. 

I think we can add a message Subject for users to subscribe. I am sorta busy now but you are welcome to make a pull request.

**Comment by smnbbrv** [comment]
@maxisam thank you for quick response. If we talk about some event-like Subject, it would also make sense to pass some metadata inside to be able to skip global message (e.g. if one wants to have a more precise message for a particular copy event)

**Comment by maxisam** [comment]
please test it at ngx-clipboard@12.1.0-beta0
Thank @surajpoddar16 for making the pull request!
