### ISSUE TITLE
Angular universal support (need reopen)

### ISSUE THREAD

**Issue by sokolandia** [maxisam/ngx-clipboard#176]
Server side rendering still gives an error in the latest version of the library:
`ERROR { Error: StaticInjectorError(AppServerModule)[InjectionToken WindowToken]: 
  StaticInjectorError(Platform: core)[InjectionToken WindowToken]: 
    NullInjectorError: No provider for InjectionToken WindowToken!
`
@angular/cli: 7.2.4
ngx-clipboard: 12.0.0

**Comment by maxisam** [comment]
what is your angular version

**Comment by sokolandia** [comment]
Angular CLI: 7.2.4
Node: 9.5.0
OS: linux x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.2.4
@angular/cdk                      7.3.6
@angular/cli                      7.2.4
@angular/material                 7.3.6
@ngtools/webpack                  7.0.7
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.6

**Comment by maxisam** [comment]
Can you check your package lock file like yarn.lock and search for ngx windows token and see if the version is 2 and above?

**Comment by sokolandia** [comment]
```
"ngx-window-token": {
      "version": "2.0.1",   
      "resolved": "https://registry.npmjs.org/ngx-window-token/-/ngx-window-token-2.0.1.tgz",   
      "integrity": "sha512-rvqdqJEfnWXQFU5fyfYt06E10tR/UtFOYdF3QebfcOh5VIJhnTKiprX8e4B9OrX7WEVFm9BT8uV72xXcEgsaKA==",   
      "requires": {
        "tslib": "1.9.3"
      }
    },
"ngx-clipboard": {
      "version": "12.0.0",
      "resolved": "https://registry.npmjs.org/ngx-clipboard/-/ngx-clipboard-12.0.0.tgz",
      "integrity": "sha512-uN5KMNIiRT7uVHfJ5lgDSb7AvfkHvMrPjIKSaptWFl+z9AsMQq7/5IW6hfxx11AUPXY/yfoP4PWHsJ9KBwfv+g==",
      "requires": {
        "ngx-window-token": "2.0.1",
        "tslib": "1.9.3"
      }
    }
```

**Comment by sokolandia** [comment]
This is the code from ngx-window-token
`export const WINDOW = new InjectionToken<Window>(
  'WindowToken',
  typeof window !== 'undefined' && window.document ? { providedIn: 'root', factory: () => window } : undefined
);`

It doesn't seem right, does it? I know it's opensource and all but common

**Comment by maxisam** [comment]
Which part?

**Comment by sokolandia** [comment]
If there is no window `new InjectionToken()` will get `undefined` as a second parameter which is invalid. For it to work it has to get `{ providedIn: 'root', factory: () => ... }` as a second parameter regardless

**Comment by maxisam** [comment]
@sokolandia  I think you are correct. Or I should change it to be optional at here

https://github.com/maxisam/ngx-clipboard/blob/493530c1db1f07c86698766a9042f9e528d3825a/projects/ngx-clipboard/src/lib/ngx-clipboard.service.ts#L10

`@Optional() @Inject(WINDOW) private window: any`

**Comment by maxisam** [comment]
please try ngx-clipboard@12.0.1-beta1

**Comment by sokolandia** [comment]
dude just drop that library and replace it with
`export const WINDOW = new InjectionToken('window', {
  providedIn: 'root',
  factory: () => typeof window !== 'undefined' ? window : null
});`

**Comment by maxisam** [comment]
Did you try it?

**Comment by maxisam** [comment]
It should be fixed according to the similar issue here. https://github.com/maxisam/ngx-progressive-image-loader/issues/12
