### ISSUE TITLE
Angular 8 Issue

### ISSUE THREAD

**Issue by ryan-bradford** [maxisam/ngx-clipboard#178]
When I load this module in a project using Angular 8.0.0-rc.0, I am given this error on start

```
WARNING in ./node_modules/ngx-clipboard/fesm5/ngx-clipboard.js 239:63-71
"export 'DOCUMENT' was not found in '@angular/platform-browser'

WARNING in ./node_modules/ngx-clipboard/fesm5/ngx-clipboard.js 242:159-167
"export 'DOCUMENT' was not found in '@angular/platform-browser'
```

On the previous version of the Angular 8 beta (14), this package worked fine, but on this version it has some issues.

**Comment by maxisam** [comment]
yeah it is because of this https://github.com/angular/angular/pull/28117
