### ISSUE TITLE
expose isCopySupported as a directive property

### ISSUE THREAD

**Issue by surajpoddar16** [maxisam/ngx-clipboard#179]
Can we expose isCopySupported as a directive property so that, users can conditionally show copy button. Right now I have to get reference of isCopySupported method from the ClipboardService in each component I want to use the directive. I can create a PR if this seems legitimate.

**Comment by maxisam** [comment]
I think so. Go ahead.

**Comment by surajpoddar16** [comment]
@maxisam seems like exposing isCopySupported will not solve this case. If NgIf is applied to the same element as the directive itself, it won't have access to the template reference variable for the same.

**Comment by surajpoddar16** [comment]
Though a user can still wrap it inside another element on which the directive can be applied

**Comment by surajpoddar16** [comment]
@maxisam Hi, I created a structural directive to support that conditionally renders target element based on isCopySupported flag. the code looks like this
```import { Directive, Input, OnInit, TemplateRef, ViewContainerRef } from '@angular/core';

import { ClipboardService } from './ngx-clipboard.service';

@Directive({
    // tslint:disable-next-line:directive-selector
    selector: '[ngxClipboardIfSupported]',
})
export class HdClipboardIfSupportedDirective implements OnInit {
    constructor(
        private _clipboardService: ClipboardService,
        private _viewContainerRef: ViewContainerRef,
        private _templateRef: TemplateRef<any>
    ) {}

    public ngOnInit() {
      if (this._clipboardService.isSupported) {
        this._viewContainerRef.createEmbeddedView(this._templateRef);
      }
    }
}
```

example implementation looks like this
```
<span
  *ngxClipboardIfSupported
  ngxClipboard
  cbContent="Foo bar"
  class="hevo-icon hevo-copy">
</span>
```

Can we provide a directive like this?

**Comment by maxisam** [comment]
yeah, I think we can. Make a pull request and I will take care of it. thx

**Comment by surajpoddar16** [comment]
created a PR https://github.com/maxisam/ngx-clipboard/pull/182

**Comment by maxisam** [comment]
it is out in ngx-clipboard@12.1.0-beta0 Thx!
