### ISSUE TITLE
About release cycle

### ISSUE THREAD

**Issue by surajpoddar16** [maxisam/ngx-clipboard#184]
Hi, a quick question, what is the release cycle for this library?

**Comment by maxisam** [comment]
There is none. Well, if the anyone tell me the beta is good, I probably will just push it.

**Comment by maxisam** [comment]
Btw, have you tried the latest beta yet? If you think it is good, I will push it life.

**Comment by surajpoddar16** [comment]
Where is the latest  beta version published?

**Comment by surajpoddar16** [comment]
Nope, I will test it today

**Comment by maxisam** [comment]
please review 12.1.0-beta2

**Comment by surajpoddar16** [comment]
Reviewed 12.1.0-beta2, things seem to work fine, you can release it. 👍

**Comment by maxisam** [comment]
It is released! Thank you for your help!
