### ISSUE TITLE
Angular 8 breaking change - version update required

### ISSUE THREAD

**Issue by edlangjr** [maxisam/ngx-clipboard#189]
After upgrading to angular 8 I am receiving the following issue:

ERROR in ./node_modules/ngx-clipboard/fesm2015/ngx-clipboard.js 175:29-37
"export 'DOCUMENT' was not found in '@angular/platform-browser'

DOCUMENT has been removed from @angular/platform-browser.  This needs to be imported from @angular/common.

**Comment by maxisam** [comment]
https://github.com/maxisam/ngx-clipboard/pull/180 

Please try the latest version

**Comment by edlangjr** [comment]
You are correct.  I missed updating this reference in my project.  Thank you for being cool.

**Comment by maxisam** [comment]
no biggie.
