### ISSUE TITLE
Add support for Angular 8

### ISSUE THREAD

**Issue by euangoddard** [maxisam/ngx-clipboard#190]
I'm just upgrading a project to Angular v8 and I'm getting a compiler error from ngx-clipboard:

```
ERROR in ./node_modules/ngx-clipboard/fesm2015/ngx-clipboard.js 172:59-67
"export 'DOCUMENT' was not found in '@angular/platform-browser'
ERROR in ./node_modules/ngx-clipboard/fesm2015/ngx-clipboard.js 175:155-163
"export 'DOCUMENT' was not found in '@angular/platform-browser'
```

It looks like the `DOCUMENT` token has now moved to be exported from `@angular/common`. I will make a PR to fix this

**Comment by euangoddard** [comment]
@maxisam do you have a time-frame for when you will release a version of the package with these changes? I'm having to patch the code in my `node_modules` right now :)

**Comment by maxisam** [comment]
@euangoddard  Please try 12.1.1 thx!

**Comment by euangoddard** [comment]
Works like a charm 🎉
