### ISSUE TITLE
Backward compatibility issue with V7

### ISSUE THREAD

**Issue by carlosptt** [maxisam/ngx-clipboard#193]
Problems compiling your library, contains warnings attached the image, I am using angular 7 and update to the version you uploaded 4 hours ago
![image](https://user-images.githubusercontent.com/33324609/59380314-d0a10d00-8d26-11e9-9c70-2f0298d8e035.png)

**Comment by carlosptt** [comment]
You should have left version 12.0.0 untouched, without requiring the angle / core 8.0.0, if you can make that change I would appreciate it since I use that component within my company

**Comment by maxisam** [comment]
https://github.com/angular/angular/issues/30413

In short, I need to recompile it with v7. Doing it now.

**Comment by maxisam** [comment]
please try 12.1.2

**Comment by carlosptt** [comment]
Nothing what I did was to stay with the version 12.1.0 until it makes the migration to Angular 8, but it is good that you have modified it: D

**Comment by maxisam** [comment]
@carlosptt ah... did you try it? does it work?

**Comment by carlosptt** [comment]
I will try to see if it runs in the angular 7 I already notify you

**Comment by carlosptt** [comment]
Ready tested perfect thank you @maxisam

**Comment by AdrianoRabello** [comment]
i m angular 10 and the same error : /
