### ISSUE TITLE
[Breaking Change 💔] 12.1.1 fails Karma test suite

### ISSUE THREAD

**Issue by bkimminich** [maxisam/ngx-clipboard#194]
The way I declared the dependency on this module as `"ngx-clipboard": "^12.1.0"` resulted in the following error when 12.1.1 came out:

```
HeadlessChrome 75.0.3770 (Linux 0.0.0) ERROR
  Uncaught TypeError: Object(...) is not a function
  at http://localhost:9876/_karma_webpack_/vendor.js:170327
HeadlessChrome 75.0.3770 (Linux 0.0.0) ERROR
  Uncaught TypeError: Object(...) is not a function
  at http://localhost:9876/_karma_webpack_/vendor.js:170327
HeadlessChrome 75.0.3770 (Linux 0.0.0) ERROR
  Uncaught TypeError: Object(...) is not a function
  at http://localhost:9876/_karma_webpack_/vendor.js:170327
```

This can be reproduced with `"ngx-clipboard": "12.1.1"`. Then pinning to `"ngx-clipboard": "12.1.0"` the test suite works fine again.

* Error log example: https://travis-ci.org/bkimminich/juice-shop/jobs/544794618
* Spotted by @greenkeeper: https://github.com/bkimminich/juice-shop/issues/1114

**Comment by bkimminich** [comment]
(This issue is probably related to #193)

**Comment by maxisam** [comment]
please try 12.1.2 thx

**Comment by bkimminich** [comment]
My @greenkeeper build is just running, and it seems to be happy with 12.1.2! Thanks!

https://travis-ci.org/bkimminich/juice-shop/builds/544976091
