### ISSUE TITLE
clean up the temp textarea

### ISSUE THREAD

**Issue by DmitryEfimenko** [maxisam/ngx-clipboard#196]
Thanks for a useful library!
My use-case is quite unique, but nonetheless, here it is:
* My website makes use of keyboard shortcuts. For example, pressing "/" will open a search bar input and put a focus on that input. The event handler that listens for the "/" ignores events if `document.activeElement` is an `input` or `textarea`.
* Once the user found the element using this search feature, the user will click on it, which will copy something into the clipboard using this library.
* Now, at this point, the user may press "/" again to search for another item and that's where the bug is. Pressing "/" does not open the search bar because after copying things into the clipboard `activeElement` becomes the temp `textarea` that this library generates [here](https://github.com/maxisam/ngx-clipboard/blob/master/projects/ngx-clipboard/src/lib/ngx-clipboard.service.ts#L73).

This issue can be easily solved if we destroy the `textarea` after using it.
I propose to replace [line 81](https://github.com/maxisam/ngx-clipboard/blob/master/projects/ngx-clipboard/src/lib/ngx-clipboard.service.ts#L81) with the following:
```ts
const toReturn = this.copyFromInputElement(this.tempTextArea);
this.destroy(this.tempTextArea.parentElement);
return toReturn;
```
I have tested this and it works for my use-case. Please let me know what you think.

**Comment by maxisam** [comment]
I understand. I wonder if you can create a option for this, like isDestoryTempEverytime. So if isDestoryTempEverytime is true, we remove the tempTextArea after copying. So people who don't care about this, they don't need to create and destroy every time.

**Comment by DmitryEfimenko** [comment]
The option for enabling/disabling this functionality sounds like a great idea! Another possible name for the option: `cleanUpAfterCopy` or `destroyAfterCopy`. I don't mind any name though - choose whatever you think is best.

Will you be doing the code change or would you like a PR?

**Comment by maxisam** [comment]
cleanUpAfterCopy sounds good to me. Welcome to make a PR. I am a bit busy now. Thx!
