### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by SinghManvir** [maxisam/ngx-clipboard#200]
The stackblitz demo is not working. It asks to install dependencies twice but then fails with the following error:

`Error in /turbo_modules/@clr/angular@2.0.2/bundles/clr-angular.umd.js (846:49)
core.ɵɵdefineInjectable is not a function`

**Comment by maxisam** [comment]
well, somehow the package can't install properly on stackblitz.com. It is not under my control tho. You can try to do it locally.
