### ISSUE TITLE
Latest version (11.1.9) incompatible with Angular v8.1.2

### ISSUE THREAD

**Issue by n-pilipovic** [maxisam/ngx-clipboard#203]
After Angular update to latest version (from version 7.2.15 to 8.1.2) this lib starter throwing error in terminal, after _ng start_ command:

**ERROR in ./node_modules/ngx-clipboard/fesm2015/ngx-clipboard.js 161:59-67
"export 'DOCUMENT' was not found in '@angular/platform-browser'**

**Comment by Obsserver** [comment]
Same issue

**Comment by vtolstov** [comment]
yes have the same issue

**Comment by glalloue** [comment]
It seems to be fixed with version 12.2.0 (tested with ionic 4.7.0 and angular 8 project)

**Comment by vtolstov** [comment]
Yes, 12.2.0 works fine,thanks

**Comment by Obsserver** [comment]
Confirming that 12.2.0 works fine.

**Comment by n-pilipovic** [comment]
Closed it as resolved.
