### ISSUE TITLE
Error after upgrading to angular 8

### ISSUE THREAD

**Issue by greatpwr** [maxisam/ngx-clipboard#209]
I am getting the following error after upgrading to angular8.  Is angular 8 supported?

ERROR in ./node_modules/ngx-clipboard/fesm2015/ngx-clipboard.js 161:59-67
"export 'DOCUMENT' was not found in '@angular/platform-browser'

I am using bootstrap@5.2.0 and angular 8.2.8

**Comment by maxisam** [comment]
It is nothing to do with bootstrap. But I think you need to update your ngx-clipbard version to the latest.

**Comment by greatpwr** [comment]
Sorry, I meant to say I am using ngx-clipboard@11.1.9  
In angular 8, DOCUMENT is removed from @angular/platform-browser, It's now importing from @angular/common.
Is this something I can contribute by starting a new branch for angular 8?

**Comment by greatpwr** [comment]
Never mind. It works after I upgraded to 12.2.1  Thanks.

**Comment by HassanAb0123** [comment]
How did u upgrade it? @greatpwr
