### ISSUE TITLE
StackBlitz example on README does not work / is outdated

### ISSUE THREAD

**Issue by ArnauAregall** [maxisam/ngx-clipboard#212]
It requires to install missing packages:
![image](https://user-images.githubusercontent.com/2873901/69366607-fb5c9d80-0c96-11ea-844a-861678977294.png)

And clicking on Install Missing Packages, unmet peer dependencies are detected:

![image](https://user-images.githubusercontent.com/2873901/69366718-35c63a80-0c97-11ea-8e6c-a80b1fce724f.png)

And after installing them, the module fails to load:

![image](https://user-images.githubusercontent.com/2873901/69366840-5ee6cb00-0c97-11ea-8bb4-3c163908b7cc.png)

Should consider upgrading the example to latest compatible Angular version of the library, or at least offer a working example out of the box.

**Comment by maxisam** [comment]
fix in 457dc57245413376a840938e3f613123945451c7
