### ISSUE TITLE
Not working with Rollup

### ISSUE THREAD

**Issue by goleary** [maxisam/ngx-clipboard#22]
I am attempting to upgrade my application to the latest version of ng2 (2.4.1) & in the process reduce the need for 3rd party code maintained outside of npm (because of AoT and rollup issues).
I'm using the latest version of your plugin, and getting the following error when I run the rollup step:
![image](https://cloud.githubusercontent.com/assets/16123225/21559364/ec9f1616-cdff-11e6-98a0-5b8ef81354e5.png)

**Comment by goleary** [comment]
I've added it to Misko's starter project here so you can repro on your own: https://github.com/goleary/angular2-rollup-build/tree/rollup-clipboard-not-working

**Comment by maxisam** [comment]
Have you checked the demo ? It should work. I used it on my own project. I use https://github.com/AngularClass/angular2-webpack-starter as base template. I think you might wanna try this one instead. It has AoT + tree shaking as well.

**Comment by goleary** [comment]
I'm not actually beginning a project with that starter, I just provided it as an minimal repro of the issue.

I've been working on my project for quite some time and switching to webpack from rollup is currently not feasible.  Did you check out the repro I provided?

**Comment by maxisam** [comment]
Do you use the most currently version in your project ? Seriously, this is pretty new, so different version shows different result. I only test the version I use.

**Comment by maxisam** [comment]
Please try 3.0.5. I think it might work.

**Comment by goleary** [comment]
Tried the new version.  Seems to be building and bundling fine, but now I'm getting a run-time error from the lib:
![image](https://cloud.githubusercontent.com/assets/16123225/21624607/a301e69e-d1bc-11e6-83e5-56d470006c3a.png)

**Comment by maxisam** [comment]
Weird. Now I have no clue. Is this the only library you can't get it work ?

**Comment by goleary** [comment]
I'm getting no errors from other libraries altho this causes my entire application to fail and stop responding.

**Comment by maxisam** [comment]
do you add this in rollup-config.js (with CommonJs to ES2015 Plugin)
```
commonjs({
  include: 'node_modules/clipboard/**',
}),

```

**Comment by goleary** [comment]
I'm using the commonjs plugin like this: `commonjs()` (default includes all commonjs libs) because If I use the syntax above it excludes other files that I need included.

**Comment by goleary** [comment]
this is what `Clipboard` appears to be:
![image](https://cloud.githubusercontent.com/assets/16123225/21627756/dac258d6-d1ce-11e6-8b4f-abcb9e4a69b5.png)

**Comment by goleary** [comment]
I've modified code in clipboard.directive.js in the following way as a workaround:
```
ClipboardDirective.prototype.ngOnInit = function () {
        var _this = this;
        var option;
        option = !!this.targetElm ? { target: function () { return _this.targetElm; } } : { text: function () { return _this.cbContent; } };
        **try {
          this.clipboard = new Clipboard(this.elmRef.nativeElement, option);
        } catch(err) {
          console.log('Error caught: Clipboard not constructor');
          this.clipboard = new Clipboard.default(this.elmRef.nativeElement, option);
        }**
        this.clipboard.on('success', function () { return _this.onSuccess.emit(true); });
        this.clipboard.on('error', function () { return _this.onError.emit(true); });
    };
```
I'm unsure what change should be made to the src file to fix the problem.  It seems like the import is behaving differently with and without rollup.

**Comment by maxisam** [comment]
Interesting. I have no idea why it acts like that. I have no idea how to generate code like that. Maybe you can try Stackoverflow ?

**Comment by maxisam** [comment]
the way I import it should be correct. https://basarat.gitbooks.io/typescript/content/docs/types/@types.html

**Comment by goleary** [comment]
https://github.com/Microsoft/TypeScript/issues/5073

**Comment by maxisam** [comment]
Does it work after update the dependency ?

**Comment by maxisam** [comment]
I think the only way to fix this is hoping clipboardjs to release a es2015 build.

Someone else have the same issue.

https://github.com/rollup/rollup-plugin-commonjs/issues/157

**Comment by goleary** [comment]
the dependency was a different issue. we are using work around for now I think my coworker is working on another repro for the issue (slightly different from what I provided above).  I'll update here when we have it

**Comment by maxisam** [comment]
Just publish a new version. Should resolve this issue. Will reopen this if the problem still exist.

**Comment by rushi216** [comment]
Any solution/updates to this issue? Stuck with same.

**Comment by maxisam** [comment]
sorry, there is no good way to do it now I think. 
https://github.com/rollup/rollup-plugin-commonjs/issues/157

**Comment by maxisam** [comment]
@rushi216  did you try the latest ngx-clipboard ?

**Comment by rushi216** [comment]
@maxisam yes, I am using 5.1.0.

Currently, I have temporarily fixed it by defining clipboard global and added it in index.html as script tag.

**Comment by maxisam** [comment]
So I think a better solution to this is remove dependency of clipboard.js

In the end, it is actually easier than figure out how to fix this.

Please try 6.0.0-beta6. Thx !
