### ISSUE TITLE
Subscribe to copyResponse$ not working

### ISSUE THREAD

**Issue by AniketBhadane** [maxisam/ngx-clipboard#229]
Angular: 8.1.0
ngx-clipboard: 12.3.0

```
  constructor(
    private clipboardService: ClipboardService,
  ) {
    this.subscribeToClipboard();
  }

  subscribeToClipboard() {
    this.clipboardService.copyResponse$.subscribe((res: IClipboardResponse) => {
      console.log('res', res);
      if (res.isSuccess) {

      } else {

      }
    });
  }

  triggerOnClick(content) {
    this.clipboardService.copyFromContent(content);
  }
```
The contents are actually copied to the clipboard when triggerOnClick is called. But the subscription to copyResponse$ does not work and I do not get any value in it when copy is done.

What could be going wrong here?

**Comment by maxisam** [comment]
It works. I just updated the demo to present this part. If you can provide a small demo on stackblitz.com, I will take a look

https://github.com/maxisam/ngx-clipboard/blob/38f131b826a0ac8bff0f63e98fcf6d667777f5a3/src/app/app.component.ts#L21-L28

**Comment by AniketBhadane** [comment]
Where does the subscribe have to be written? Is it only in the main root app component, or it should work even in other components?

**Comment by maxisam** [comment]
ah it works everywhere as long as they are under the same dependency injection tree. If you have more issue in dependency injection, please ask the question in stackoverflow. thanks!

**Comment by AniketBhadane** [comment]
The example in the repository is with Angular 7. Have you tried with Angular 8?

**Comment by AniketBhadane** [comment]
It is still not working for me. Whether I place the code in root app component or some other component. I don't know why the issue was closed

**Comment by maxisam** [comment]
> The example in the repository is with Angular 7. Have you tried with Angular 8?

There is no different between 7 and 8. 8 mostly improves on build process.

You can download the repo and upgrade to 8 and test it, or you can create a demo on stackblitz.com.

I closed it because it is not a bug in this project. It is more like an angular general issue that should be asked on stackoverflow.

if you can create a demo on stackblitz.com showing it is a bug, I will reopen the issue. Thanks!
