### ISSUE TITLE
Error in ngx-clipboard.service.d.ts

### ISSUE THREAD

**Issue by jacqueslareau** [maxisam/ngx-clipboard#235]
I get this error on Angular 8.2.14, ts 3.5.3, ngx-clipboard 13.0.0

ERROR in ../node_modules/ngx-clipboard/lib/ngx-clipboard.service.d.ts:16:9 - error TS1086: An accessor cannot be declared in an ambient context.

16     get isSupported(): boolean;
           ~~~~~~~~~~~

**Comment by maxisam** [comment]
umm, I guess you should try Angular 9 or use v12.

**Comment by jacqueslareau** [comment]
Yes. Downgraded to v12. In the changelog it says: adding support for angular 9. Does not say removing support for <8. Might consider adding a notice somewhere that v13 requires Angular 9.

**Comment by maxisam** [comment]
It should popup a warning during package update.

https://github.com/maxisam/ngx-clipboard/blob/d46bd257384112575d0fa9f3500f578aeaa83f6c/projects/ngx-clipboard/package.json#L27-L30

**Comment by jacqueslareau** [comment]
Thank you! Just trying to save time to others. Thanks for your contribution!

**Comment by AlonsoK28** [comment]
Could you specify that it refers to the version of `ngx-clipboard`, I thought it would refer to the version of `Node.Js` and so install `nvm`  then I tried to put `ngx-clipboard: ^ 12.0.0` and it worked
