### ISSUE TITLE
cbOnSuccess kicks in but not copying

### ISSUE THREAD

**Issue by lukaberdeen** [maxisam/ngx-clipboard#240]
I'm trying to copy text into clipboard, it kicks in with cbOnSuccess fine however text not landing in the clipboard (when I paste nothing appears).

I tried this
`<button 
  ngxClipboard
  [cbContent]="'target string'"
  class="share-button">
  <span class="fa fa-clipboard share-button__icon"></span>
  <span class="share-button__text">&nbsp;&nbsp;Copy link</span>
</button>`

also with service 

`this._clipboardService.copyFromContent(text)`

and it kick in the method but "text" doesn't go to clipboard and when I do paste nothing is there.

I'm using angular8 and "ngx-clipboard": "12.3.1", there are no errors in the console it simply doesn't copy text to real clipboard.

**Comment by maxisam** [comment]
Well, have you tried demo yet?
