### ISSUE TITLE
readme, no

### ISSUE THREAD

**Issue by hugo-valcourt** [maxisam/ngx-clipboard#254]
Hi, in the Readme you have :
```
Dependencies
If you need to use it on 2.x, please use version 7.x.x.
If you need to use it on 4.x, please use version 8.x.x.
If you need to use it on 5.x, please use version 10.x.x.
If you need to use it on 8.x, please use version 12.x.x.
If you need to use it on 9.x, please use version 13.x.x.
```

The version for 7.0 is not there: 
`If you need to use it on 7.x, please use version x.x.x.`

Could you please add it ?

Thanks

**Comment by maxisam** [comment]
welcome to make a pr :-)

**Comment by hugo-valcourt** [comment]
I can make a PR, but I need to know the good version. Is it 11.1.9 for Angular 7 ?

11.x.x?

**Comment by maxisam** [comment]
To be honest, I kinda lost track of that as well. Your guess is as good as mine. :-)
