### ISSUE TITLE
package does not work w/Angular 10 + Ivy enabled

### ISSUE THREAD

**Issue by 62mkv** [maxisam/ngx-clipboard#258]
Execute `npm install --save ngx-clipboard` (version `14.0.1` is installed)

Add the declaration to `app.module.ts`: 

```
import { ClipboardModule } from 'ngx-clipboard';
```

Got an error from Webpack: 
```
ERROR in node_modules/ngx-copypaste/app/ngx-copypaste/ngx-copypaste.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of MiddlewareUiAppModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-copypaste) which declares NgxCopyPasteModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update i
f so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

1 export declare class NgxCopyPasteModule {
                       ~~~~~~~~~~~~~~~~~~
```

are there any workarounds possible ? (that would not involve disabling Ivy, cause that unleashes a host of errors)

**Comment by 62mkv** [comment]
after some googling around, it seems that issuing `ngcc` command resolves that specific problem, but now I have different one:

```
ERROR in src/main/webapp/app/entities/request-history-step/request-history-step-detail.component.html:35:46 - error NG8002: Can't bind to 'cbContent' since it isn't a known property of 'button'.

35                         <button ngxClipboard [cbContent]="'requestHistoryStep.payload?.payload'" [container]="payload">Copy</button>
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/main/webapp/app/entities/request-history-step/request-history-step-detail.component.ts:12:16
    12   templateUrl: './request-history-step-detail.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component RequestHistoryStepDetailComponent.
src/main/webapp/app/entities/request-history-step/request-history-step-detail.component.html:35:98 - error NG8002: Can't bind to 'container' since it isn't a known property of 'button'.

35                         <button ngxClipboard [cbContent]="'requestHistoryStep.payload?.payload'" [container]="payload">Copy</button>
                                                                                                    ~~~~~~~~~~~~~~~~~~~~~

```

that's what I have in the template: 

```html
                <dd>
                    <span>
                        <pre #payload>{{ requestHistoryStep.payload?.payload }}</pre>
                        <button ngxClipboard [cbContent]="'requestHistoryStep.payload?.payload'" [container]="payload">Copy</button>
                    </span>
                </dd>
```

can anyone suggest, what might be wrong here?

**Comment by maxisam** [comment]
NgxCopyPasteModule is nothing to do with this library.

**Comment by maxisam** [comment]
apparently you import a wrong library

**Comment by 62mkv** [comment]
Hi @maxisam sorry, I've screwed the WebPack error in original post (now deleted). But the issue still holds, can you look at the first comment?

**Comment by maxisam** [comment]
i'm sorry, but i don't have time to handle support. You might wanna try stackoverflow. And you should definitely try the demo code.

**Comment by 62mkv** [comment]
thanks for your attention! but can you confirm that this library is capably to work w/ Angular 10 with Ivy enabled?

**Comment by 62mkv** [comment]
just in case anyone stumbles on this later: https://stackoverflow.com/questions/65078359/how-to-add-ngx-clipboard-or-any-similar-library-to-jhipster-6-10-angular-10-ba

**Comment by maxisam** [comment]
yes, it works with IVY enabled. You should try demo.

**Comment by 62mkv** [comment]
Yeah, I've figured it already, thank you. So I was actually confused because webpack would occasionally produce this "not an Ivy module" but actually I was just importing it in the wrong module.
Thanks for your awesome work!
--
Sent from Mail.ru app for Android Monday, 30 November 2020, 07:57pm +02:00 from Sam Lin  notifications@github.com :
