### ISSUE TITLE
IE 11 - Issue with ngx-clipboard 13.0.1 for Angular 9.1.7

### ISSUE THREAD

**Issue by kil5152** [maxisam/ngx-clipboard#259]
When angular route contains **"redirectTo"** and **"pathMatch"** properties (see below), the IE 11 has the following error when clicking the navigation link and using **ngx-clipboard 13.0.1**. If I would downgrade from **ngx-clipboard 13.01** to **ngx-clipboard 12.3.1**, the navigation link works fine in IE 11.

```
 {
    path: '',
    component: SendComponent,
    redirectTo: 'send',
    pathMatch: 'full'
  }
```

![image](https://user-images.githubusercontent.com/5281535/102907421-05c20b80-4444-11eb-9fbb-f91ee7f342a8.png)

**Comment by maxisam** [comment]
I don't think this is ngx-clipboard's issue. And I never heard of this kinda issue as well.
