### ISSUE TITLE
unable to load transpiler to transpile ngx-clipboard, needs to specify transpiler explicitly, Systemjs

### ISSUE THREAD

**Issue by GopiAnnan** [maxisam/ngx-clipboard#26]
unable to load transpiler to transpile ngx-clipboard, 
needs to specify transpiler explicitly when I use Systemjs

**Comment by maxisam** [comment]
i don't really use system.js. So I might need some help on this.

**Comment by maxisam** [comment]
close for now. I will reopen if there is any more question.
