### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export index.js

### ISSUE THREAD

**Issue by bkostic10** [maxisam/ngx-clipboard#27]
I am using the ngx-clipboard in the solution http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/

I am constantly having the issue: Uncaught SyntaxError: Unexpected token export on \node_modules\ngx-clipboard\index.js. The error appears on site loading (after I added the ClipboardModule to app.module.ts)

**Comment by maxisam** [comment]
You might wanna check your tsconfig. The module setting should be es2015.

**Comment by maxisam** [comment]
close for now. I will reopen if there is any more question.

**Comment by bkostic10** [comment]
When I set the module to es2015, i get an Uncaught SyntaxError: Unexpected token import on the boot-client.ts:1
The line is **import 'angular2-universal-polyfills/browser';**

**Comment by maxisam** [comment]
sorry, you can try to ask this on stackoverflow.
