### ISSUE TITLE
Getting Error when running application with ngx-clipboard  

### ISSUE THREAD

**Issue by AngularTx** [maxisam/ngx-clipboard#29]
I have installed the ngx-clipboard package and

1. added entry in the appmodule.ts 

Add sample code in the component as given in the demo 

I get the below error when running the application : 

---
export * from './dist';
Uncaught SyntaxError: Unexpected token export(…)
----

**Comment by maxisam** [comment]
how about run the whole demo code ? The problem of your situation is probably the module setting in tsConfig.

**Comment by AngularTx** [comment]
is there anything very specific which needs to be taken care of in the Tsconfig file? 

Also , would like to know if any other application adds some data to the clipboard,
Can I use this module to get that data from my Angular2 application running on the same machine/session. probably I will never add any clipboard content via this package. I would like to just retrieve it and perform some actions. I am using IE browser with Angular 2.4.8 version.

**Comment by maxisam** [comment]
module setting should be ES2015 in tsConfig. 

I don't understand the second question. Do you mean you wanna add content to clipboard directly ?

**Comment by AngularTx** [comment]
I would like to read the data from the clipboard which is added by other application . So I will not add anything to the clipboard using your package, but would like to just read the data from clipboard.

**Comment by maxisam** [comment]
I see. But I think you misunderstood what it does. This library doesn't do any paste. What it does is putting data into clipboard. There is no way you can read it from this.

**Comment by maxisam** [comment]
close for now. I will reopen if there is any more question.
