### ISSUE TITLE
cbOnSuccess eventEmitter not working

### ISSUE THREAD

**Issue by hags033** [maxisam/ngx-clipboard#307]
As of version 15.x.x cbOnSuccess event emitter is no longer working. This works in the previous version 14.0.2. 

Modified stackblitz https://stackblitz.com/edit/github-nn4hwx-6v83rt?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Comment by rahuldimri** [comment]
This works correctly. Verified by creating samples with version 14.0.2 and 15.1.x. Please close this issue or provide more details

**Comment by hags033** [comment]
In the stackblitz I have added an output to the first button ```(cbOnSuccess)="onSuccess($event)"``` and in the component
```
     onSuccess(event) {
        alert('copy success');
    }
```

This onSuccess method in the component does not fire as of version 15.x.x of the library.

**Comment by rahuldimri** [comment]
I was able to get "copy success" alerts. PFA the screenshot.
<img width="1723" alt="Screenshot 2022-06-14 at 11 18 41 PM" src="https://user-images.githubusercontent.com/107100022/173654352-3d7a397b-ad3a-4153-ae59-ac19c92ae24d.png">

**Comment by hags033** [comment]
Closing as my best guess is it's a conflict with one of our other dependencies. We moved from Angular 10 to Angular 13 and ngx-clipboard 14 to ngx-clipboard 15 and all 4 places cbOnSuccess was used no longer work.

**Comment by Eraldo** [comment]
`cbOnSuccess` does also not fire for me using Angular 14.

**Comment by Darkein** [comment]
I have the same problem with `angular` 14.1.3 and `ngx-clipboard` 15.1.0
