### ISSUE TITLE
Error in clipboard.directive.ts

### ISSUE THREAD

**Issue by larxenne** [maxisam/ngx-clipboard#32]
```
[default] .../node_modules/ngx-clipboard/dist/clipboard.directive.d.ts:1:1 
    Cannot find type definition file for 'clipboard'.
[default] .../node_modules/ngx-clipboard/dist/clipboard.directive.d.ts:3:28 
    Cannot find module 'clipboard'.
[default] Checking finished with 2 errors
```

Any idea ?

**Comment by larxenne** [comment]
Yea the demo code is building fine, but what in my configuration is wrong ?
It's the only package where I have an issue.

Here is my configuration
`{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "mapRoot": "./",
    "module": "es5",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}
`

**Comment by maxisam** [comment]
"module": "es5" should be "es2015"

**Comment by larxenne** [comment]
`{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "mapRoot": "./",
    "module": "es2015",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es2015",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}
`

Exact same issue with that version

**Comment by maxisam** [comment]
node and npm version ?

**Comment by larxenne** [comment]
Node : 6.9.4
Npm: 3.10.10

**Comment by maxisam** [comment]
do you use webpack or systemjs ?

**Comment by larxenne** [comment]
Project was generated with : https://github.com/angular/angular-cli

So webpack

**Comment by maxisam** [comment]
what cli version ?

**Comment by berhir** [comment]
I get the same error when I run `ngc -p ./tsconfig-aot.json`.
It works when I downgrade to v3.0.5 of ngx-clipboard.

**Comment by larxenne** [comment]
"angular-cli": "1.0.0-beta.21",

**Comment by larxenne** [comment]
Thanks berhir, it's working for me aswell with the downgrade

**Comment by maxisam** [comment]
3.0.6 is update for angular 4.0. I will investigate more on it.

**Comment by maxisam** [comment]
I think it is caused by https://github.com/maxisam/ngx-clipboard/commit/5bffa8441caf6fd05015363f606e785f2f4bf818

I just released an new version correct it. Thanks !

**Comment by larxenne** [comment]
Thank you for your reactivity !
I'm gonna try the new version latter today and I'll let you know.
