### ISSUE TITLE
webpack warning: Cannot find SourceMap

### ISSUE THREAD

**Issue by berhir** [maxisam/ngx-clipboard#33]
I use webpack to bundle my project and it always shows this warning:
```
WARNING in ./~/ngx-clipboard/dist/index.js
Cannot find SourceMap '/home/travis/build/maxisam/ngx-clipboard/index.js.map': Error: Can't resolve './/home/travis/build/maxisam/ngx-clipboard/index.js.map' in 'C:\...\node_modules\ngx-clipboard\dist'
 @ ./~/ngx-clipboard/index.js 1:0-23
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

I checked the index.js file and found this line at the end:
`//# sourceMappingURL=/home/travis/build/maxisam/ngx-clipboard/index.js.map`

The index.js.map file is in the same directory as the index.js but the path is wrong. Can you fix this?

I get the same warning in this file:
`WARNING in ./~/ngx-clipboard/dist/clipboard.directive.js`

But the path is correct in the `index.umd.js` file.

**Comment by maxisam** [comment]
it is actually generated by webpack. I am not sure how to fix it. But I am thinking about using Rollup instead of webpack now. I probably will do that when I have time next week

**Comment by maxisam** [comment]
Just publish 5.0.0. It should take care this problem.
