### ISSUE TITLE
Latest version incompatible with Angular CLI

### ISSUE THREAD

**Issue by Ismaestro** [maxisam/ngx-clipboard#35]
I've installed latest version like this:

`npm install ngx-clipboard --save`

I'm using Angular CLI and there is a problem with v5.0.3 of this module.

I have to use 4.0.0 in my package.json. 

Please update de documentation and the module in order to use Webpack and AngularCLI. SystemJS is in decline

**Comment by maxisam** [comment]
what version of CLI you are using ?

**Comment by Ismaestro** [comment]
More info:

`@angular/cli: 1.0.0-rc.1`
`node: 7.1.0`
`os: darwin x64`
`@angular/cli: 1.0.0-rc.1`
`@angular/common: 2.4.9`
`@angular/compiler: 2.4.9`
`@angular/core: 2.4.9`
`@angular/forms: 2.4.9`
`@angular/http: 2.4.9`
`@angular/platform-browser: 2.4.9`
`@angular/platform-browser-dynamic: 2.4.9`
`@angular/router: 3.4.9`
`@angular/compiler-cli: 2.4.9`

In package.json:

`"clipboard": "^1.6.1",`
`"ngx-clipboard": "^5.0.3",`

And when I try to do:

`import {ClipboardModule} from 'ngx-clipboard';`

It says:

`ERROR in src/app/shared/shared.module.ts (36,48): Cannot find module 'ngx-clipboard'.)`

But if I install `"ngx-clipboard": "4.0.0",` it works!

Note that I have to change path in angular-cli.json...

**Comment by maxisam** [comment]
could you try cli 1.0 instead of RC 1?

**Comment by JSMike** [comment]
Which version of typescript is included in your project?

**Comment by Ismaestro** [comment]
@JSMike My version of typescript is:
`"typescript": "~2.0.3"`

And @maxisam yes of course I can install cli 1.0 but the thing is that I don't want to work with it. I prefer to work with the release candidate. 

The thing here, is why v4.0.0 works and v5.0.2 does not?

Thanks :)

**Comment by maxisam** [comment]
Please check the demo code. It works on demo/angularCli. Maybe you should upgrade typescript to latest ?

**Comment by JSMike** [comment]
FYI, Angular 2.x only supports typescript ~2.0.0 so he should he would have to upgrade to the latest typescript 2.0.x, not 2.1.x or 2.2.x

**Comment by maxisam** [comment]
@JSMike Oh ! I didn't know that. Sorry @Ismaestro  you might wanna try manually modify the package.json to see if it works. If it does, I will push another release.

**Comment by maxisam** [comment]
FYI

**Comment by Ismaestro** [comment]
@maxisam That's it. now it works! thanks! 

:)

**Comment by maxisam** [comment]
Cool. It is still kinda weird why it didn't work. 

I don't fully understand why removing typings & adding module make this work.

**Comment by Ismaestro** [comment]
I think watching the changes that the problem was the path. In 4.0.0 it was like this:
`dist/index.js`
and now it has a new folder bundle:
`./dist/bundle/ngxClipboard.umd.min.js`

So when I tried to import the module typescript didn't find it...

Whatever, now it works, thanks!
