### ISSUE TITLE
Source files are missing

### ISSUE THREAD

**Issue by berhir** [maxisam/ngx-clipboard#36]
I previously got warnings because the paths to the source map files were wrong (#33).
I updated to version 5.0.3 and the paths are correct.
But now the source files are missing and so I get this warning: 
```
WARNING in ./~/ngx-clipboard/dist/index.js
Cannot find source file '../index.ts': Error: Can't resolve '../index.ts' in 'C:\[...]\node_modules\ngx-clipboard\dist'
 @ ./src/app/app.module.ts 14:0-48
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/main.ts
```

Please add the source files to the node module. Because the map files do not make sense without the source files.  
Thanks!

**Comment by maxisam** [comment]
f25699fe514612c1a2a9939186bbe1656aecca65 should take care this. Thx !
