### ISSUE TITLE
Could not find a declaration file for module 'ngx-clipboard'

### ISSUE THREAD

**Issue by tombpain** [maxisam/ngx-clipboard#37]
Hi,

Just upgraded to Angular 4 and trying to do AOT compilation I get the following while compiling using:

node_modules/.bin/ngc -p src/tsconfig-aot.json

Error at /Users/*/src/app/app.module.ts:31:33: Could not find a declaration file for module 'ngx-clipboard'. '/*/node_modules/ngx-clipboard/dist/index.js' implicitly has an 'any' type.

This is using the latest version of ngx clipboard.

Any help is appreciated.

Cheers, Tom

**Comment by maxisam** [comment]
Could you check with demo/angularCli ?

**Comment by maxisam** [comment]
close the issue for now. Will reopen it if there is any more problem.
