### ISSUE TITLE
AOT Compilation fails for Angular CLI 1.0.0

### ISSUE THREAD

**Issue by arutnik** [maxisam/ngx-clipboard#39]
I get these errors when I use ng build --prod with CLI version 1.0.0 and version 5.0.9 of ngx-clipboard.

ERROR in C:/git/fspg-web-full-stack/guestrec-frontend/src/$$_gendir/node_modules/ngx-clipboard/src/clipboard.directive.ngfactory.ts (36,20): Property 'targetElm' is private and only accessible within class 'ClipboardDirective'.
C:/git/fspg-web-full-stack/guestrec-frontend/src/$$_gendir/node_modules/ngx-clipboard/src/clipboard.directive.ngfactory.ts (43,20): Property 'cbContent' is private and only accessible within class 'ClipboardDirective'.
C:/git/fspg-web-full-stack/guestrec-frontend/src/$$_gendir/node_modules/ngx-clipboard/src/clipboard.directive.ngfactory.ts (61,53): Property 'cbOnSuccess' is private and only accessible within class 'ClipboardDirective'.
C:/git/fspg-web-full-stack/guestrec-frontend/src/$$_gendir/node_modules/ngx-clipboard/src/clipboard.directive.ngfactory.ts (62,53): Property 'cbOnError' is private and only accessible within class 'ClipboardDirective'.

ERROR in C:/git/fspg-web-full-stack/guestrec-frontend/src/$$_gendir/node_modules/ngx-clipboard/src/clipboard.directive.ngfactory.ts (36,20): Property 'targetElm' is private and only accessible within class 'ClipboardDirective'.
C:/git/fspg-web-full-stack/guestrec-frontend/src/$$_gendir/node_modules/ngx-clipboard/src/clipboard.directive.ngfactory.ts (43,20): Property 'cbContent' is private and only accessible within class 'ClipboardDirective'.
C:/git/fspg-web-full-stack/guestrec-frontend/src/$$_gendir/node_modules/ngx-clipboard/src/clipboard.directive.ngfactory.ts (61,53): Property 'cbOnSuccess' is private and only accessible within class 'ClipboardDirective'.
C:/git/fspg-web-full-stack/guestrec-frontend/src/$$_gendir/node_modules/ngx-clipboard/src/clipboard.directive.ngfactory.ts (62,53): Property 'cbOnError' is private and only accessible within class 'ClipboardDirective'.

It looks like it's because you have private @input variables on the directive class. With AOT compilation these cannot be private.

**Comment by maxisam** [comment]
Could you try 5.0.8 and see if it works?

**Comment by arutnik** [comment]
I can confirm the error does not appear with version 5.0.8

**Comment by maxisam** [comment]
5.0.10 is release. Thank you !
