### ISSUE TITLE
Suggestion upon improving the Event emit

### ISSUE THREAD

**Issue by ewolution94** [maxisam/ngx-clipboard#40]
Hi,

currently the directive only emits a true as event whether its 'success' or 'error'. I would suggest that instead of a boolean, you could emit the event itself so that in the (cbOnSucces) you can refer to the text for example:

@Output() public cbOnSuccess: EventEmitter< Event >  = new EventEmitter< Event >();

@Output() public cbOnError: EventEmitter< Event > = new EventEmitter< Event >();

..

this.clipboard.on('success', (e) => this.cbOnSuccess.emit(e));
this.clipboard.on('error', (e) => this.cbOnError.emit(e));

**Comment by maxisam** [comment]
Please try 5.1.0 Thanks !
