### ISSUE TITLE
tslint error in ClipboardDirective

### ISSUE THREAD

**Issue by VR9980** [maxisam/ngx-clipboard#41]
Error: 
./node_modules/ngx-clipboard/src/clipboard.directive.ts[12, 5]: In the class "ClipboardDirective", the directive input property "targetElm" should not be renamed.Please, consider the following use "@Input() targetElm: string"

tsconfig.json:
 "exclude": [
    "bin",
    "node_modules",
    "node_modules/ngx-clipboard/src/**"
  ]

tslint run:
       tslint rules: npm run lint

**Comment by maxisam** [comment]
Well, this will be a no fix. I don't see anything bad to rename it in this case. And I think this shouldn't be an issue anyway because you should use the code from `/dist` not from `/src`.

**Comment by danielmatthew** [comment]
@VR9980 Encountered this too. Our fix was similar to yours:

```
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/ngx-clipboard/**/*"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/ngx-clipboard/**/*"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/ngx-clipboard/**/*"
    }
  ],
```

**Comment by VR9980** [comment]
Thx
