### ISSUE TITLE
6.0.5 errors due to BrowserModule

### ISSUE THREAD

**Issue by achimha** [maxisam/ngx-clipboard#43]
With 6.0.5 I get an error on my lazily loaded modules using the `ClipboardModule`:

Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

I do not load `ClipboardModule` in my main bundle but only in lazily loaded modules using

```
imports: [
  ClipboardModule.forRoot()
]
```

The problem is that it imports `BrowserModule`, it should import `CommonModule` instead.

**Comment by achimha** [comment]
A better approach for the singleton pattern can be found here: https://github.com/angular/angular/issues/13854

**Comment by maxisam** [comment]
I just released 6.0.6 address this issue by using CommonModule

However, when I tried the pattern you suggest, I'm kinda stuck. Please check[ this branch ](https://github.com/maxisam/ngx-clipboard/tree/feature/singleton_pattern)

I think by using that pattern, somehow DI doesn't really work anymore.

**Comment by achimha** [comment]
Thanks for the fix.

I haven't had a chance to test your tree. The code looks correct to me. What exactly happens? I have [used the pattern successfully](https://github.com/xmaestro/angular2-recaptcha/blob/master/lib/captcha.service.ts) in one of my modules.

**Comment by maxisam** [comment]
I know. I went thru that one. For some reasons, clipboard service doesn't get WindowSrv instance.
In your case, ngZone should have been created before loading the module. But in this case, WindowSrv is create at the same time. 
But I try `new WindowSrv()` and it doesn't work either.

**Comment by maxisam** [comment]
I figured it out. I forgot to put windowSrv in providers. duh ! Please try 7.0.1

**Comment by achimha** [comment]
Working fine, thank you! Much better now :smile: I hope one day Angular will provide a more convenient pattern for this use case.
