### ISSUE TITLE
No provider for ClipboardService!

### ISSUE THREAD

**Issue by utd1878** [maxisam/ngx-clipboard#45]
I'm using Webpack and run the install and then add the ClipboardModule to my module file.  When I add the button to my template, I see the above error.

`import { ClipboardModule } from 'ngx-clipboard';`

`  imports: [ // import Angular's modules
    BrowserModule,
    FormsModule,
    HttpModule,
    ClipboardModule,
    RouterModule.forRoot(ROUTES, { useHash: true, preloadingStrategy: PreloadAllModules })
  ],`

Template: 
`<button class="btn btn-default" type="button" [ngxClipboard]="field_field.id">copy</button>`

Sorry if this is the wrong venue, just not sure what else I'm missing for this to be erring like this.

**Comment by maxisam** [comment]
try **ClipboardModule.forRoot()**

**Comment by utd1878** [comment]
Great...thank you for your quick response.

For anyone coming in after, this did the trick.
