### ISSUE TITLE
Peer Dependencies of >=2.4.1

### ISSUE THREAD

**Issue by fkclient** [maxisam/ngx-clipboard#47]
Hi,
Is it possible to reduce the peer dependency to 2.2.1 (my version) or even lower (2.0.0)? 
Thanks
FK

**Comment by maxisam** [comment]
I thought it doesn't matter ? It doesn't stop you from building or including in your project right ? 
It should work in your project.

**Comment by maxisam** [comment]
please try 7.0.3
