### ISSUE TITLE
Module '"{path}/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

### ISSUE THREAD

**Issue by amyrhsieh** [maxisam/ngx-clipboard#48]
I just installed version 7.0.2.

After importing ClipboardModule and listing it in @NgModule imports in my app module, I get this error: Module '"{path}/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.

My version of Angular is 2.4.0.

Please advise, thanks.

**Comment by maxisam** [comment]
Ah....didn't see this one coming. InjectionToken is introduced in angular 4. I guess you should use 7.0.1. They are basically the same thing. 7.0.2 uses InjectionToken.

**Comment by maxisam** [comment]
Ok, I make it clear on readme. Thanks !

**Comment by amyrhsieh** [comment]
Thanks for your reply. I went all the way back to v6.0.5, and I still saw the import of InjectionToken in clipboard.service.ts, thus still got the same error. So I will use v6.0.2.

**Comment by maxisam** [comment]
please try 7.0.4. I removed everything rely on InjectionToken for that branch.

**Comment by amyrhsieh** [comment]
Great, 7.0.4 works for me! Thanks for such prompt replies!!
