### ISSUE TITLE
@angular/core has no exported member 'InjectionToken' in v7.0.3

### ISSUE THREAD

**Issue by d4nyll** [maxisam/ngx-clipboard#49]
When trying to build my application, I get the following error:

`ERROR in /build/node_modules/ngx-clipboard/src/clipboard.service.ts (2,18): Module '"/build/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.`

I am using Angular v2.4.10 and `ngx-clipboard` v7.0.3. From my understanding, `InjectionToken` is only available in Angular v4, so maybe it needs to be removed from [this line](https://github.com/maxisam/ngx-clipboard/blob/v7.0.3/src/clipboard.service.ts#L2)?

**Comment by maxisam** [comment]
It is causing by DOCUMENT, this is from 4.0 as well. I will make the change later today

**Comment by maxisam** [comment]
please try 7.0.4
