### ISSUE TITLE
Directive throws when copy not supported

### ISSUE THREAD

**Issue by achimha** [maxisam/ngx-clipboard#50]
In some environments, access to the clipboard is not allowed. I see various error reports from my users where `ngxClipboard` throws loading the component. This is due to

https://github.com/maxisam/ngx-clipboard/blob/master/src/clipboard.directive.ts#L23

I don't think this directive should throw in its initializer. This breaks the whole component using it in environments where there is no clipboard access.

**Comment by maxisam** [comment]
will make the change later today

**Comment by maxisam** [comment]
please try v8.01

**Comment by achimha** [comment]
Thanks for the fix!
