### ISSUE TITLE
Can't compile when "noImplicitAny" is true 

### ISSUE THREAD

**Issue by mattytommo** [maxisam/ngx-clipboard#51]
There's a few compile errors when including the package within an Angular CLI project. You get the follow errors when building following an NPM install:

```
ERROR in /node_modules/ngx-clipboard/src/clipboard.service.ts (10,9): Parameter 'document' implicitly has an 'any' type.
/node_modules/ngx-clipboard/src/clipboard.service.ts (11,9): Parameter 'window' implicitly has an 'any' type.
/node_modules/ngx-clipboard/src/clipboard.service.ts (102,52): Parameter 'doc' implicitly has an 'any' type.
/node_modules/ngx-clipboard/src/clipboard.service.ts (102,57): Parameter 'win' implicitly has an 'any' type.

ERROR in /node_modules/ngx-clipboard/src/clipboard.directive.ts (27,63): Parameter 'button' implicitly has an 'any' type.
/node_modules/ngx-clipboard/src/clipboard.directive.ts (42,26): Parameter 'succeeded' implicitly has an 'any' type.
/node_modules/ngx-clipboard/src/clipboard.directive.ts (42,37): Parameter 'copiedContent' implicitly has an 'any' type.
```

The changes are nothing too drastic, just explicitly defining the types of the mentioned variables. I'll create a pull request shortly with the changes if you could get them merge into the NPM version that would be great.

**Comment by mattytommo** [comment]
Well I just submitted a commit to the master branch, but I

**Comment by mattytommo** [comment]
Incorrectly closed this, apologies.

**Comment by maxisam** [comment]
Do you set "noImplicitAny"="true" ? It is default false in CLI

**Comment by mattytommo** [comment]
I'm not able to submit a pull request with my changes unfortunately as I don't have permission.

**Comment by maxisam** [comment]
huh ? I believe you can. There are couple people did that before.

**Comment by mattytommo** [comment]
Yeah when I try and create a new pull request within GitHub for Windows from my branch angular-cli-fix into master I get "You don't have permission to push your changes to this repo". Any ideas?

We use noImplicitAny yeah as we've agreed to keep that on. We don't use skipLibCheck though, I'll take a look at that.

**Comment by maxisam** [comment]
You can't push to this repo, You can only submit pull request.

**Comment by mattytommo** [comment]
Yeah I get that error when I'm hitting "Send pull request".

**Comment by maxisam** [comment]
that's odd. there is actually no permission to stop people from making pull request.

**Comment by mattytommo** [comment]
My apologies, I think I was doing it wrong. It's my first commit on GitHub to another repo. I didn't realise I had to fork it first, make the change and the create the pull request. It looks like it has gone through now.

**Comment by maxisam** [comment]
please try v8.0.2. Thx

**Comment by deKaantje** [comment]
Hi @maxisam! Has this 'implicit any fix' also found its way to the v7.x.x versions for Angular 2.x? Or only in 8.0.2 and up?

Thanks!

**Comment by maxisam** [comment]
@deKaantje You can skip tslint for the library with  skipLibCheck = true.
