### ISSUE TITLE
@angular/core has no exported member 'InjectionToken' is still there.

### ISSUE THREAD

**Issue by moonflare** [maxisam/ngx-clipboard#54]
Hi @maxisam,

It seems issue #49 that has been fixed in `v7.0.4` is still there in all 3 versions (8.0.0, 8.0.1 and 8.0.2). Can you please have a look?

Thanks for your work!

**Comment by maxisam** [comment]
8.X.X is for Angular 4.x.x. That line is correct and needed in Angular 4

7.XX is for Angular 2.x.x

There is no functionality difference between these 2 versions.

**Comment by paulappz** [comment]
@maxisam . am having the same error. how do i update to v7.0.4. tired this "npm install ngx-clipboard --save" but still having the same error "Module '"C:/Users/Paul/Desktop/PP/Ionic2Ang2 Default - Copy/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
"

**Comment by moonflare** [comment]
@paulappz Try `npm install ngx-clipboard@7.0.4  --save`, when you run the command above, it installs the latest version. 

Another thing you can do is to manually add `"ngx-clipboard": "7.0.4"` into your `package.json` file under `dependencies` and after you save the changes, run `npm install`
