### ISSUE TITLE
Can't compile version 7.0.4 with angular 2.x

### ISSUE THREAD

**Issue by mario595** [maxisam/ngx-clipboard#55]
Hi,
when I try to compile with `ng build --prod` a project created with angular-cli 1.0.0, I've got the following error:

`ERROR in Error encountered resolving symbol values statically. Could not resolve type Document (position 11:45 in the original .ts file), resolving symbol ClipboardService in /Users/-/node_modules/ngx-clipboard/src/clipboard.service.ts`

I am using version 7.0.4 of ngx-clipboard and this is my `tsconfig.json`:
`
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es6",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016"
    ]
  }
}
`

**Comment by maxisam** [comment]
That's odd. Can you create a repo showing this issue ?

**Comment by klavs1us** [comment]
Quote mario595. Same problem Here:

 14% building modules 37/37 modules 0 activeFailed on type {"filePath":"/front-end/node_modules/ngx-clipboard/src/clipboard.service.ts","name":"ClipboardService","members":[]} with error Error: Error encountered resolving symbol values statically. Could not resolve type Document (position 11:45 in the original .ts file), resolving symbol ClipboardService in /Users/luka/Code/g2020/front-end/node_modules/ngx-clipboard/src/clipboard.service.ts

**Comment by maxisam** [comment]
That is odd. Could you try demo code ? or create a repo ?

**Comment by maxisam** [comment]
close for now. Will reopen if there is more question

**Comment by philandrews-ixxus** [comment]
I'm having this issue with my project as well.  Angular 2.4.9 ngx-clipboard 7.0.4.  I can also duplicate pretty much immediately with the demo code.

1. Checkout angular2.0.0 branch
2. in /demo/angularCli run npm install
3. run ng build --prod
->  pxa@pxa-PC MINGW64 /c/dev/checkouts/ngx-clipboard/demo/angularCli (angular2.0.0)
$ ng build --prod
 10% building modules 5/5 modules 0 activeFailed on type {"filePath":"C:/dev/checkouts/ngx-clipboard/demo/angularCli/node_modules/ngx-clipboard/src/clipboard.service.ts","name":"ClipboardService","members":[]} with error Error: Error encountered resolving symbol values statically. Could not resolve type Document (position 11:45 in the original .ts file), resolving symbol ClipboardService in C:/dev/checkouts/ngx-clipboard/demo/angularCli/node_modules/ngx-clipboard/src/clipboard.service.ts                                                                                                Hash: 65ec4e16340e355c7d67                Time: 9288ms
chunk    {0} polyfills.2f4fce266794794866ce.bundle.js (polyfills) 158 kB {4} [initial] [rendered]
chunk    {1} main.12547e2093af48258542.bundle.js (main) 679 bytes {3} [initial] [rendered]
chunk    {2} styles.d41d8cd98f00b204e980.bundle.css (styles) 69 bytes {4} [initial] [rendered]
chunk    {3} vendor.2211f29df0c8f461ed91.bundle.js (vendor) 842 kB [initial] [rendered]
chunk    {4} inline.d092f130f12a6d1a6981.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in Error encountered resolving symbol values statically. Could not resolve type Document (position 11:45 in the original .ts file), resolving symbol ClipboardService in C:/dev/checkouts/ngx-clipboard/demo/angularCli/node_modules/ngx-clipboard/src/clipboard.service.ts

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\dev\checkouts\ngx-clipboard\demo\angularCli\src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts

Not sure what other information is relevant.
Windows 10 using GIT Bash from Git for Windows v2.12.2(2)

$ npm -version
3.10.10

$ ng version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.1.2
node: 6.10.0
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.1.2
@angular/compiler-cli: 2.4.10

Hopefully this info is helpful.  Please re-open this issue.  I will try dropping back to 7.0.3 or bisecting between the two.

**Comment by maxisam** [comment]
I pretty sure it works.

Here is the plunker to prove it.

https://plnkr.co/edit/zpMDmJ0A31in7t4HAWex?p=preview

**Comment by philandrews-ixxus** [comment]
Plunker uses JIT to compile apps, but this issue is only present when you try to build the app for Production (`ng build --prod`).  Plunker's linting isn't nearly as strict and it also doesn't run the AoT compilation so it won't trigger the issues @mario595 @klavs1us and I are seeing, you need to run the ng build from a command line.

**Comment by maxisam** [comment]
That makes sense. I will try it later.

**Comment by philandrews-ixxus** [comment]
Awesome, thanks!

**Comment by maxisam** [comment]
please try 7.0.6.

**Comment by philandrews-ixxus** [comment]
For what it's worth, I was able to get the demo compiling by changing:
clipboard.directive.ts line 31
```
- @HostListener('click', ['$event.target']) private onClick(button) {
+ @HostListener('click', ['$event.target']) public onClick(button) {
```

And clipboard.service.ts line 11:
```
- @Inject(DOCUMENT) private document: Document,
+ @Inject(DOCUMENT) private document: any,
```

Using 'any' feels bit hacky but it's so worth it.  A production build shaves about 6 MB off the size of the generated /dist/ folder...and that's just for your demo.

But it does seem to work testing the app in chrome and Firefox 54.

**Comment by philandrews-ixxus** [comment]
7.0.6 works like a dream!  Thanks!
