### ISSUE TITLE
Does not work with 'disabled' input/textareas

### ISSUE THREAD

**Issue by transparentech** [maxisam/ngx-clipboard#56]
Hi. Thanks for your work on this plugin!

I wanted to use this on a disabled textarea, but the copy didn't work. There were no errors in the console. It simply did not copy the text in the text area. Removing the 'disabled' attribute from the textarea made the copy work.

I know that there are other ways of doing this (like with [cbContent]) but it would make it more flexible if it could handle 'disabled' input and textareas.

**Comment by maxisam** [comment]
Thanks. But I don't think it can work on disabled, since you can't actually select text from disable element. It will throw an error when you try to copy. 

IMHO, You have 2 options, use readonly or cbContent. Good luck
