### ISSUE TITLE
No provider for ClipboardService!

### ISSUE THREAD

**Issue by abdulqadir93** [maxisam/ngx-clipboard#57]
I thought I found the fix when I saw issue https://github.com/maxisam/ngx-clipboard/issues/45. But when I try .forRoot(), typescript complains that `Property .forRoot() does not exist on type 'typeof ClipboardModule'. When I look inside my node_modules/ngx-clipboard/src/index.ts, I see that indeed that's true. Am I missing anything? I have v8.0.2 installed.

The end goal is to use the isSupported method inside the service so I can show/hide the copy action. Is there another way to do this since it's not documented?

**Comment by maxisam** [comment]
after v7.0.1, it no longer requires forRoot. You can use the service by injected it to your component.

**Comment by abdulqadir93** [comment]
For now, I've added the ClipboardService in my module as a provider which fixes the error:

    @NgModule({
        imports: [...., ClipboardModule],
        providers: [..., ClipboardService] // throws no provider error otherwise!
    })

But I should be able to access the service after importing the ClipboardModule without explicitly adding the service right? Do you think that makes sense?

**Comment by maxisam** [comment]
You are correct. I think it is because the pattern I used for avoiding duplicated injection causes this issue. And I think there is no way to have both ways. 

If you are going to use clipboard service, you need to inject it at root module, or any module before current module.

**Comment by abdulqadir93** [comment]
So what are your thoughts about an additional input to the directive that is something similar to [hideIfNotSupported]="true"?

**Comment by maxisam** [comment]
I think hide is not a good UX solution. Besides, you can add service to your provider like what you did now. It won't create 2 services. 

Moreover, if it is not supported, it will return isSuccess = false, so you can handle it with something like a notification.

**Comment by iamjesse98** [comment]
app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { ErrorHandler, NgModule } from '@angular/core';
import { IonicApp, IonicErrorHandler, IonicModule } from 'ionic-angular';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';
import { Clipboard } from '@ionic-native/clipboard';

import { MyApp } from './app.component';
import { HomePage } from '../pages/home/home';

@NgModule({
  declarations: [
    MyApp,
    HomePage
  ],
  imports: [
    BrowserModule,
    IonicModule.forRoot(MyApp)
  ],
  bootstrap: [IonicApp],
  entryComponents: [
    MyApp,
    HomePage
  ],
  providers: [
    StatusBar,
    SplashScreen,
    Clipboard,
    {provide: ErrorHandler, useClass: IonicErrorHandler}
  ]
})
export class AppModule {}

home.ts
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
//import { translate } from 'some-translator';
import { Clipboard } from '@ionic-native/clipboard';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, private clipboard: Clipboard) {
  	let focused = false;
  	let text = '';
  	let result = '';
  }

  etom(x) {
  	return translate(x);
  }

  copy(t) {
  	this.clipboard.copy(t)
  }

}


home.html
<ion-header>
  <ion-navbar>
    <ion-title>
     	Emoji Translate
    </ion-title>
  </ion-navbar>
</ion-header>

<ion-content>

  <ion-card class="input-wrapper" [style.border]="focused ? '2px solid #cddc39' : 'none'">
  <ion-card-content>
    <textarea class="input" (focus)="focused = true" (blur)="focused = false" [(ngModel)]="text" (keyup)="result = etom(text)"></textarea>
  </ion-card-content>
</ion-card>

<ion-card class="output-wrapper">
  <ion-card-content>

  {{ result }}
    
  </ion-card-content>
</ion-card>

<button ion-button block (click)="copy(result)">copy to clipboard</button>

</ion-content>



this is not working
😠

**Comment by maxisam** [comment]
plunker example does work. If you have more question. Please ask it on StackOverflow.
