### ISSUE TITLE
still having the "node_modules//index"' has no exported member 'InjectionToken'."

### ISSUE THREAD

**Issue by paulappz** [maxisam/ngx-clipboard#58]
@maxisam . am having the same error. how do i update to v7.0.4. tired this "npm install ngx-clipboard --save" but still having the same error "Module '"C:/Users/Paul/Desktop/PP/Ionic2Ang2 Default - Copy/node_modules//index"' has no exported member 'InjectionToken'.

**Comment by maxisam** [comment]
You need to use `npm install ngx-clipboard@7.0.4 --save`

**Comment by paulappz** [comment]
ok thanks
