### ISSUE TITLE
[cbContent]  not working

### ISSUE THREAD

**Issue by Crizstian** [maxisam/ngx-clipboard#59]
the [cbContent] does not work in angular 4, i have tried the other option but i need to defien an inputTarget but since i am displaying a list of urls dynamically i cant create inputtargets dynamically

the [cbContent] grabs the value, but doesnt put it in the clipboard

**Comment by maxisam** [comment]
It works http://embed.plnkr.co/PD4Ap8/

**Comment by Crizstian** [comment]
Its not working even  with the version of the plunker, i am using Angular 4 with CLI

this my code

```
                         <tr *ngFor="let u of urls?.publishUrls; let i = index">
                              <td>
                                <!-- <span class="link">{{u}}</span> -->
                                <div class="input-group">
                                 <input type="text" class="form-control" [value]="u" >
                                 <span class="input-group-btn">
                                   <button class="btn btn-primary" type="button" ngxClipboard [cbContent]="u" (cbOnSuccess)="what($event)" >copy</button>
                                 </span>
                               </div>
                              </td>
                          </tr>
```

**Comment by maxisam** [comment]
I don't understand. It is working in my plunker. What do you mean by "Its not working even with the version of the plunker"?
