### ISSUE TITLE
Not working with Aot and Rollup

### ISSUE THREAD

**Issue by ankit213** [maxisam/ngx-clipboard#61]
Error - While building my app with aot and rollup gets this error.

![image](https://user-images.githubusercontent.com/9895825/27865829-bc0ca2de-61b1-11e7-9586-5424dfad0e3e.png)

**Here is my package.json**

     {
     "name": "demo",
     "version": "1.0.0",
     "description": "",
     "main": "index.js",
     "scripts": {
    "aot": "node_modules/.bin/ngc -p wwwroot/tsconfig-aot.json",
    "rollup": "node_modules/.bin/rollup -c wwwroot/rollup-config.js",
    "cleanup": "rimraf wwwroot/app/aot && rimraf wwwroot/build.js"
     },
    "author": "",
    "license": "ISC",
    "dependencies": {
    "angular/animations": "4.1.3",
    "angular/common": "4.1.3",
    "angular/compiler": "4.1.3",
    "angular/compiler-cli": "4.1.3",
    "angular/core": "4.1.3",
    "angular/forms": "4.1.3",
    "angular/http": "4.1.3",
    "angular/material": "2.0.0-beta.6",
    "angular/platform-browser": "4.1.3",
    "angular/platform-browser-dynamic": "4.1.3",
    "angular/platform-server": "4.1.3",
    "angular/router": "4.1.3",
    "angular/upgrade": "4.1.3",
    "core-js": "2.4.1",
    "ngx-clipboard": "8.0.3",
    "rxjs": "5.4.0",
    "systemjs": "0.20.13",
     "zone.js": "0.8.11"
     },
    "devDependencies": {
    "ngx-window-token": "0.0.2"
     "rollup": "0.43.0",
     "rollup-plugin-commonjs": "8.0.2",
     "rollup-plugin-node-resolve": "3.0.0",
     "rollup-plugin-uglify": "2.0.1",
     "typescript": "2.2.2",
     "rimraf": "2.6.1"
     }
     }

**Here is my tsconfig-aot.json**

      {
     "compilerOptions": {
     "target": "es5",
     "module": "es2015",
     "moduleResolution": "node",
     "sourceMap": true,
     "emitDecoratorMetadata": true,
     "experimentalDecorators": true,
     "lib": [ "es2016", "dom" ],
     "noImplicitAny": false,
     "suppressImplicitAnyIndexErrors": true
     },
    "files": [
    "app/app.module.ts",
    "app/main-aot.ts"
    ],

    "angularCompilerOptions": {
    "genDir": "app/aot",
    "skipMetadataEmit": true
    }
    }

**Here is my rollup.config.js**

    import nodeResolve from 'rollup-plugin-node-resolve';
    import commonjs from 'rollup-plugin-commonjs';
    import uglify from 'rollup-plugin-uglify';

    export default {
    entry: 'wwwroot/app/main-aot.js',
    dest: 'wwwroot/build.js', // output a single application bundle
    sourceMap: false,
    format: 'iife',
    onwarn: function (warning) {
        // Skip certain warnings

        // should intercept ... but doesn't in some rollup versions
        if (warning.code === 'THIS_IS_UNDEFINED') { return; }

        // console.warn everything else
        console.warn(warning.message);
     },
     plugins: [
        nodeResolve({ jsnext: true, module: true }),
        commonjs({
            include: 'node_modules/**',
        }),
        uglify()
    ]
    }

Thanks in advance

**Comment by maxisam** [comment]
sorry, I don't use rollup very often. You might want to try to ask on StackOverflow for this.

**Comment by OleksiiZubko** [comment]
downgraded to 5.0.1, works fine with AOT

**Comment by hkashlan** [comment]
I have same issue :(

**Comment by maxisam** [comment]
v11.1.0 should take care of this.
