### ISSUE TITLE
This won't compile strict for me

### ISSUE THREAD

**Issue by MZachmann** [maxisam/ngx-clipboard#63]
I'm getting three errors.

1) clipboard.service.ts(1,18): error TS6133: 'InjectionToken' is declared but never used.
which is pretty much exactly what it says, and is resolved by removing the declaration
2) clipboard.directive.ts(26,55): error TS6133: 'onClick' is declared but never used.
which is resolved by making the method Public instead of Private
3) clipboard.directive.ts(26,63): error TS6133: 'button' is declared but never used.
which is resolved by making it _button

Thanks.

**Comment by maxisam** [comment]
thx, just updated it

**Comment by MZachmann** [comment]
thanks

**Comment by seyfert** [comment]
I just installed the latest version (v8.0.3) from npm and it is still a problem in the npm release.  Did you publish this change?

```
ERROR in [at-loader] ./node_modules/ngx-clipboard/src/clipboard.directive.ts:26:55
    TS6133: 'onClick' is declared but never used.

ERROR in [at-loader] ./node_modules/ngx-clipboard/src/clipboard.service.ts:1:18
    TS6133: 'InjectionToken' is declared but never used.
```

**Comment by maxisam** [comment]
please try 8.0.4. I thought it would automatically publish. It turns out there was an error blocking the CI. 

It seems like InjectionToken is needed for AoT to build successfully.
