### ISSUE TITLE
could be run delayed ?

### ISSUE THREAD

**Issue by erata** [maxisam/ngx-clipboard#64]
hi, i use ngx-clipboard with java api result. i try to copy returned result from api service but it does not copy for the first attempt because of service delay.  ngx-clipboard runs normally intantly copy, but i try to delayed copy. is there a way to succeed it firt attempt too.

**Comment by maxisam** [comment]
Your problem is not really causing by ngx-clipboard. I think you should disable the whole element until you load your data from backend api.
