### ISSUE TITLE
Errors with noUnusedLocals

### ISSUE THREAD

**Issue by hiro-hori** [maxisam/ngx-clipboard#65]
In my project, we use stricter TypeScript option i.e.`noUnusedLocals`
I saw compilation error from ngx-clipboard.

```
src/clipboard.directive.ts(3,5): error TS6133: 'ElementRef' is declared but never used.
src/clipboard.service.ts(1,60): error TS6133: 'InjectionToken' is declared but never used.
```

It seems easy to fix, so I tried to fix it.
But it was difficult.

After I deleted importing InjectToken from src/clipboard.service.ts, I met a new error.
```
src/clipboard.service.ts(105,14): error TS4023: Exported variable 'CLIPBOARD_SERVICE_PROVIDER' has or is using name 'InjectionToken' from external module "/work/ngx-clipboard/node_modules/@angular/core/src/di/injection_token" but cannot be named.
```

That error seems https://github.com/Microsoft/TypeScript/issues/5711

I really want to solve this problem, does anyone have good ideas?

**Comment by maxisam** [comment]
yeah, I have no idea how to fix the 2nd one. However, I fixed the first one.  I think you can use  "skipLibCheck": true to suppress this.

**Comment by hiro-hori** [comment]
> I think you can use "skipLibCheck": true to suppress this.

Thank you for advice!

But... I think what you are saying is wrong.
First, We've already use `skipLibCheck` option.

Second If setting skipLibCheck=true, the compiler skips type checking of *.d.ts files.
But ngx-clipboard does not have d.ts file, doesn't it?

> `--skipLibCheck` Skip type checking of all declaration files (*.d.ts).
https://www.typescriptlang.org/docs/handbook/compiler-options.html

---
For this argument's information, I paste our tsconfig.

```json
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es6",
      "dom"
    ],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "../dist/out-tsc",
    "skipLibCheck": true,
    "sourceMap": true,
    "strictNullChecks": true,
    "target": "es5"
  }
}
```

**Comment by maxisam** [comment]
It has d.ts. Check your node_module folder. I think you might have 2 tsConfigs one for build one for IDE. I believe skipLibCheck is the answer. Maybe you can check with Stackoverflower on this.

**Comment by linsolas** [comment]
Hello all,

I wanted to use the ngx-clipboard library, but faced also this TSLint error. After trying - without luck - to exclude the library from TSLint configuration, I've tried to simply removed the two unused declarations. Unlike @hiro-hori, I didn't encounter any issue afterwards, and the library works great.

Some information that may help: 

* @angular/core v4.3.5
* @angular/cli v1.3.1
* @typescript v2.4.2
* @tslint v5.6.0

**Comment by linsolas** [comment]
For information, I changed my import from:

```ts
import { ClipboardModule } from 'ngx-clipboard';
```

to:

```ts
import { ClipboardModule } from 'ngx-clipboard/dist';
```

and the error is now gone (as I rely on JS and not on TS files now)

**Comment by maxisam** [comment]
@linsolas what version of ngx-clipboard do you use? I think this might be related to #69

**Comment by linsolas** [comment]
@maxisam I've used the latest one, which means 8.0.4.

**Comment by sandro-csimas** [comment]
The same here!
This is my tsconfig.json:
````
{
  "compilerOptions": {
    "baseUrl": "./src",
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "strictNullChecks": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "removeComments": true,
    "skipLibCheck": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "lib": ["es6", "dom"]
  },
  "typeRoots": [
    "../node_modules/@types",
    "./types"
  ]
}
````

**Comment by sandro-csimas** [comment]
@maxisam, with the latest version (8.1.1) I got only one error:
````
ERROR in /home/sandro/chatz-website/node_modules/ngx-clipboard/src/clipboard.service.ts
(1,60): error TS6133: 'InjectionToken' is declared but never used.
````
````
import { Inject, Injectable, Optional, Renderer, SkipSelf, InjectionToken } from '@angular/core';
````
This can be easily solved by removing ````InjectionToken```` since its not used in this file.

**Comment by maxisam** [comment]
@sandro-csimas as I mentioned before, I actually don't know how to fix it. I think it might be typescript's issue. I can't remove that import and build successfully.

**Comment by sandro-csimas** [comment]
@maxisam , ````InjectionToken```` is not used in this file.
````
ngx-clipboard/src/clipboard.service.ts
````

**Comment by maxisam** [comment]
I know. You can try to build it yourself.

**Comment by sandro-csimas** [comment]
@maxisam , OK, I will try.

**Comment by maxisam** [comment]
https://travis-ci.org/maxisam/ngx-clipboard/builds/259478307 This was the build record for the commit trying to remove that import. But maybe typescript fix the bug now if so, feel free to submit a PR.
