### ISSUE TITLE
Error with Webpack/Ionic 2

### ISSUE THREAD

**Issue by CelsoSantos** [maxisam/ngx-clipboard#69]
Hi,

I'm using ngx-clipboard@7.0.6 and unlike other issues I have seen around here, I have no problems doing a build with the `--prod` flag.

However, once I try to run the application I get the following error on Chrome:
```
Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/dev/ionic/node_modules/ngx-clipboard/src/index.js'
```

When taking a look at what the code produces, I noticed that ngx-clipboard DID build, but the correct path would be `'/Users/dev/ionic/node_modules/ngx-clipboard/dist/index.js'`. (notice the dir is `dist` instead of `src`)

I don't think it makes a difference, but here's my Ionic project tsconfig.json:
```
{
	"compilerOptions": {
		"allowSyntheticDefaultImports": true,
		"declaration": false,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"lib": [
			"dom",
			"es2015"
		],
		"module": "es2015",
		"moduleResolution": "node",
		"sourceMap": true,
		"target": "es6"
	},
	"include": [
		"src/**/*.ts"
	],
	"exclude": [
		"node_modules"
	],
	"compileOnSave": false,
	"atom": {
		"rewriteTsconfig": false
	}
}
```

How can I solve this issue? Why is this build outdir and webpack build version not matching the paths correctly?

**Comment by CelsoSantos** [comment]
Also, let me add another question which is:

Why are we getting the .ts files when doing `npm install` instead of getting a ready-made build like, for instance, ng2-translate ??

**Comment by maxisam** [comment]
well, it is just convenient if someone wanna debug through. It since it is pretty small, I don't think having source in it would causing any issue. 

Back to your original question, I don't know because I don't use ionic. Maybe you can try the latest version?

I think the main entry defined in package.json might be the reason causing that issue. The latest version might fix it already.

**Comment by CelsoSantos** [comment]
Hi Sam, unfortunately I cannot used the latest version at the moment since
I am, for now at least, stuck on Angular 2.2.1.

I've forked the repo and try there.

One thing I need to add is that apparently only my builds are causing the
error. When building the same exact code and commands on my machine I get
that Chrome error.. Really weird

**Comment by maxisam** [comment]
you don't need to switch to latest right now. You just create a test project like the way you are setting but use angular 4 and you can test against with the latest code. If latest code work, it shouldn't be too hard to fix.

**Comment by dweber019** [comment]
Have the same issue with angular 4.

imported the module into the page module and then this error is showing:

Uncaught (in promise): Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/tzhweda9/Desktop/Dipl Repos/TEKO-dipl-fontend/node_modules/ngx-window-token/index.js.map' at Error (native) Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/tzhweda9/Desktop/Dipl Repos/TEKO-dipl-fontend/node_modules/ngx-window-token/index.js.map' at Error (native) at Object.378 (http://localhost:8100/build/8.js:298:7) at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30) at Object.142 (http://localhost:8100/build/8.js:12:81) at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30) at Object.377 (http://localhost:8100/build/8.js:194:77) at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30) at Object.476 (http://localhost:8100/build/8.js:320:79) at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30) at Object.475 (http://localhost:8100/build/8.js:306:69) at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)

**Comment by maxisam** [comment]
Please try 8.1.1. Will reopen if the problem still exists.

**Comment by jasonz1987** [comment]
have the same issue when i try 8.1.1.

Error: ./node_modules/ngx-clipboard/src/clipboard.directive.ts
Module build failed: Error: ENOENT: no such file or directory, open '/Users/tuo3/git/drip-ionic3/node_modules/ngx-clipboard/src/clipboard.directive.js'
 @ ./src/pages/about/about.ngfactory.ts 35:0-61
 @ ./src/pages/about/about.module.ngfactory.ts
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts,./node_modules/ngx-clipboard/src/clipboard.service.ts
Module build failed: Error: ENOENT: no such file or directory, open '/Users/tuo3/git/drip-ionic3/node_modules/ngx-clipboard/src/clipboard.service.js'
 @ ./src/pages/about/about.module.ngfactory.ts 22:0-59
 @ ./src lazy
 @ ./node_modules/ionic-angular/util/ng-module-loader.js
 @ ./src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts,./node_modules/ngx-clipboard/src/index.ts

**Comment by bergergit** [comment]
Are there any solutions for this error? I'm also trying to compile with AOT (using --prod) and I get the same error, even with 8.1.1.

**Comment by DouglasLapsley** [comment]
I'm also having this problem.  Ionic 3, Angular 5.2.11, ngx-clipboard: "^8.1.1".

Build command:

`ionic build --aot --minifyjs --minifycss`

Error on build: 

`Error: ./node_modules/ngx-clipboard/src/clipboard.directive.ts
Module build failed: Error: ENOENT: no such file or directory, open '/MYPATH/node_modules/ngx-clipboard/src/clipboard.directive.js'`

Any pointers would be welcome.  Thank you!
