### ISSUE TITLE
Template parse errors: Can't bind to 'ngxClipboard' since it isn't a known property of 'button'

### ISSUE THREAD

**Issue by inpercima** [maxisam/ngx-clipboard#70]
Hi,

I use the current version of ngx-clipboard (8.0.4) and angular 4.3.5 with angular-material 2.0.0-beta.8. I followed the plunker example but it doesn't work. The browser console shows the error.

The code:

```
<button md-raised-button color="primary" class="full-width" [ngxClipboard]="copyToClipboard">copy</button>
...
<textarea mdInput readonly placeholder="myText" #copyToClipboard>myText</textarea>
```

If I inlcude `ClipboardModule` or not in the app.module.ts, the error occurs so I think the module is not loaded. But why? Is there a known issue?

Thanks.

**Comment by inpercima** [comment]
My mistake. After some days not working on it, I realised the problem. I do have multiple modules. I have to put the code in the correct one. ;) Thx for this extension.

**Comment by RenaldasK** [comment]
Having same issue

**Comment by schandrakandi** [comment]
@inpercima  @RenaldasK  Facing the same issue. Any help on the same ?

**Comment by inpercima** [comment]
@schandrakandi If you have multiple modules, do not include the import in the app.module but in you sub.module. Then it should work.

```javascript
import { ClipboardModule } from 'ngx-clipboard';
...
...

@NgModule({
  declarations: [
    ...
  ],
  imports: [
    ClipboardModule,
    ...
```

**Comment by schandrakandi** [comment]
@inpercima it does not help :-(

**Comment by 8tomo8** [comment]
If anyone is having this issue while building an Ionic app with the --prod flag make sure you import ClipboardModule in the pages module you are using it in. Delete it from app.module

**Comment by inpercima** [comment]
@RenaldasK @schandrakandi Did you get it solved?

**Comment by chris1340check** [comment]
Did someone find a solution?
