### ISSUE TITLE
How to copy hidden input text?

### ISSUE THREAD

**Issue by g-guth** [maxisam/ngx-clipboard#71]
I need to copy a text from a hidden input like:

`                 <div class="btn btn-xs btn-default">
                        <span [ngxClipboard]="pass" class="action-subject">
                              Copy
                        </span>
                  </div>
                  <div class="portlet-body">
                    <input class="form-control" type="hidden" #pass [value]="password" readonly>
                  </div>`

But it is not working, is there some workaround to do that?

**Comment by maxisam** [comment]
try `[cbContent]="'target string'"`

**Comment by g-guth** [comment]
Can't bind to 'cbContent' since it isn't a known property of 'span'. ("actions">

I m using the release version 8.0.4

**Comment by maxisam** [comment]
Please check demo and plunker.  If you have more question, please go to StackOverflow.

**Comment by g-guth** [comment]
I did, and changed the plunker example to [cbContent] and not work as well

**Comment by g-guth** [comment]
Theres no [cbContent] example on plunker.
