### ISSUE TITLE
Can't use the ngxClipboard in dynamically generated components

### ISSUE THREAD

**Issue by alejanp** [maxisam/ngx-clipboard#73]
I'm using ngx-clipboard 8.0.4.
In our application we are using a dynamically generated component for the user actions (click on buttons).
It seems like I cannot apply directives to dynamically generated components so I'd need to access the clipboard service directly and call `copyFromContent `and providing the text I need copied.

What I propose is to export the `ClipboardService` in the index so it can be called from any user initiated event in any component.

**Comment by maxisam** [comment]
yeah, I think it would work. Do you mind to make a pull request?

**Comment by alejanp** [comment]
I'll take care of it. It would be my first PR in github so bear with me if I don't follow some guidelines.
Cheers!

**Comment by maxisam** [comment]
Please try 8.1.0. Thanks!
