### ISSUE TITLE
Problem ngx-clipboard 8.1.0

### ISSUE THREAD

**Issue by williangd** [maxisam/ngx-clipboard#76]
In version 8.1.0 the demo used in the plunker does not work. 

**Way that does not work:** (text1 is a property of App component) (Works on 8.0.0)

`<button class="btn btn-default" [class.btn-success]= "isCopied1" type="button" ngxClipboard [cbContent]="text1" (cbOnSuccess)="isCopied1 = true">copy</button>`

**Way that works:**

```
<div class="input-group">
 <input type="text" class="form-control" [(ngModel)]="text2" placeholder="content will be copy after click the copy button" #inputTarget>
  <span class="input-group-btn">
   <button class="btn btn-default" [class.btn-success]= "isCopied2" type="button" [ngxClipboard]="inputTarget"(cbOnSuccess)="isCopied2 = true">copy</button>
  </span>
</div>
```

**Comment by maxisam** [comment]
It works on 8.1.1 now. Thx!
