### ISSUE TITLE
Suggestion: remove core-js as peer dependency

### ISSUE THREAD

**Issue by soumak77** [maxisam/ngx-clipboard#77]
It looks like `core-js` is not used by the module, but it is included as part of the demo source.  I am using the latest version of Ionic and this module works without installing `core-js`.  Therefore, shouldn't `core-js` be removed as a peer dependency since it is only needed to demo the module?

**Comment by maxisam** [comment]
Well, I believe core-js is for browser compatibility, so it should still be there.

**Comment by soumak77** [comment]
I am using Ionic with cordova-browser

**Comment by maxisam** [comment]
Yeah, I know but it is for older browsers.
