### ISSUE TITLE
Angular universal support

### ISSUE THREAD

**Issue by Starscream27** [maxisam/ngx-clipboard#82]
Hi,

It would be great if ngx-clipboard had [angular universal](https://github.com/angular/universal) support for server-side rendering. 

The major problem is the usage of `document` and `window`, which are [not available on the server](https://github.com/angular/universal#universal-gotchas).

**Comment by maxisam** [comment]
I don't see too much benefit to make it run on the server side. You should swap this component with a dummy one on the server side and load it on the client side.

**Comment by Starscream27** [comment]
Yep indeed it's useless on the server. I'm just asking that you follow the [Angular Universal guidelines](https://github.com/angular/universal#universal-gotchas) so that your package is compatible with server side rendering. This will spare users of your awesome package the need for swaping the component with a dummy one manually.

**Comment by maxisam** [comment]
It is pretty easy to have an app module specifically for server and without including ngxClipboard.

**Comment by maxisam** [comment]
Well, I think you are right. Welcome to make a pull request.
