### ISSUE TITLE
[suggest] the `Renderer` has deprecated!

### ISSUE THREAD

**Issue by cipchk** [maxisam/ngx-clipboard#84]
[position](https://github.com/maxisam/ngx-clipboard/blob/master/src/clipboard.directive.ts#L18).

Also, `copyFromContent` why need depend on `Renderer`?

**Comment by maxisam** [comment]
Will change to Renderer2 in the future. Using renderer is recommended by Angular team.

**Comment by cipchk** [comment]
```typescript
renderer.invokeElementMethod(inputElement, 'select');
renderer.invokeElementMethod(inputElement, 'setSelectionRange', [0, inputElement.value.length]);
```

And

```typescript
inputElement.select();
inputElement.setSelectionRange(0, inputElement.value.length);
```

what is the difference between them?

**Comment by maxisam** [comment]
Please check with the angular document. In short, it is better for different platforms.
