### ISSUE TITLE
AOT build issue with version 5.0.1

### ISSUE THREAD

**Issue by SunYuanOnly** [maxisam/ngx-clipboard#88]
node_modules\_ngx-clipboard@8.1.1@ngx-clipboard\src\clipboard.directive.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property

![Uploading %I[790DL]VIO9YAA45{9545.png…]()

**Comment by phra** [comment]
the screenshot link is not working..

**Comment by SunYuanOnly** [comment]
![http://www.sunyuan.info/images/1.png](http://www.sunyuan.info/images/1.png)
![http://www.sunyuan.info/images/2.png](http://www.sunyuan.info/images/2.png)

**Comment by phra** [comment]
did you tried with the latest version?

**Comment by SunYuanOnly** [comment]
Now that the problem is solved。 thanks 
 
1,  ``` ng server --preserve-symlinks  ```

2 or update .angular-cli.json

``` 
 "defaults": {
    "styleExt": "css",
    "component": {},
    "build": {
      "preserveSymlinks": true
    }
 ```

**Comment by maxisam** [comment]
can anyone try 8.1.3? thanks!

**Comment by jhcao23** [comment]
@maxisam it solved my app crash issue. So it looks like `8.1.3` might be another stable version for `Angular 5`! Cheers!

**Comment by maxisam** [comment]
close this issue and special thanks to @topce and @phra for helping the angular5 upgrade.
