### ISSUE TITLE
Uncaught Error: Unexpected value 'ClipboardModule' imported by the module 'WorkflowCanvasModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by jdgomezb** [maxisam/ngx-clipboard#91]
Hey I've updated to the `"ngx-clipboard": "^8.1.2",` and now my Angular app broke. Do you know if this is an issue with this version? or any other component?

What can I do to overcome this error? I've gone and reverted to `"^8.1.1"` and the problem persist so it tells me that it may be related to an integration with Angular Cli or something.

Has anyone seen this recently?

**Comment by stephenheard** [comment]
Getting the same error... no additional info to provide at this time, will update if I figure out what is causing it in my app.

**Comment by stephenheard** [comment]
Quick question @jdgomezb, did you also just upgrade to Angular 5?  I updated this morning.

**Comment by jdgomezb** [comment]
I fixed the issue by reverting to `8.1.1` and removing the `^`, then I cleared the `node_modules` and did an `npm install`

Still the issue might be there with the latest version and something else, and probably the latest Angular version.

**Comment by stephenheard** [comment]
Same thing worked for me.  Thanks.

**Comment by hahn-kev** [comment]
I've got an issue with the upgrade too, but mine's a bit different
`Metadata version mismatch for module D:/my_dev/Gis/Frontend/node_modules/ngx-clipboard/dist/index.d.ts, found version 4, expected 3`

From doing a bit of searching it seems this error is related to a mismatch in Angular versions, I'm still using angular 4.x but it looks like version `8.1.2` upgraded to angular 5.

Deleting and rolling back fixed the issue for me too.

**Comment by bjornharvold** [comment]
I had to downgrade to 8.1.1 as well. Running Angular 5.

**Comment by ntswor** [comment]
I downgraded too to 8.1.1 (running Angular 4.4.6) because of the same issue.

**Comment by topce** [comment]
My colleague has a same issue  
it is working in aot mode 
`ng serve --aot --dev`
but not in 
`ng serve --dev`
probably typescript version in this library should be **2.4.2** and not 2.6.1

**Comment by dbaranovsky** [comment]
Having the same issue for 8.1.2. I'm using SystemJS loader mapping to dist/bundles/ngxClipboard.umd.js and NgModule is missed there. With 8.1.1 works fine
