### ISSUE TITLE
SystemJS loading error

### ISSUE THREAD

**Issue by simianarmy** [maxisam/ngx-clipboard#92]
When trying to load my SystemJS app using the instructions in the README, I get an error about ngx-window-token:

Error loading http://localhost:8000/ngx-window-token as "ngx-window-token" from http://localhost:8000/node_modules/ngx-clipboard/dist/bundles/ngxClipboard.umd.js
	    at new g (http://localhost:8000/en-us/node_modules/zone.js/dist/zone.min.js:1:13005)

My systemjs.config.js:
'ngx-clipboard': 'npm:ngx-clipboard/dist/bundles/ngxClipboard.umd.js'

I also tried:
'ngx-clipboard': 'npm:ngx-clipboard'

with similar errors.  Using 8.1.1 but also tried 8.1.2

**Comment by maxisam** [comment]
You might wanna check the plunker in readme. If you have more question please ask it on Stackoverflow. I don't really use SystemJS. Thanks!
