### ISSUE TITLE
Uncaught Error: Unexpected value 'ClipboardModule' imported by the module 'X'.  Please add a @NgModule annotation

### ISSUE THREAD

**Issue by MarkPieszak** [maxisam/ngx-clipboard#95]
Related https://github.com/maxisam/ngx-clipboard/issues/91

@maxisam 
Hey Sam 👋 , So it looks like it's still be happening in the latest 8.1.3, with a project using Angular v 4.4.5. Trying to figure out what could be the root cause of it in the library.

We pinned to 8.1.1 for now.

cc/ @lcusimano

**Comment by maxisam** [comment]
I think it is related to this one https://github.com/angular/angular/issues/19607

**Comment by MarkPieszak** [comment]
Ah shoot you're right, maybe we could just do a 9.x release here that is for 5+ only? Good find!

**Comment by maxisam** [comment]
Yeah, I already did that. Thx
