### ISSUE TITLE
ng build --prod error  ERROR in ./node_modules/_ngx-clipboard@8.1.3@ngx-clipboard/src/clipboard.directive.ts Module build failed: Error: /web_5/node_modules/_ngx-clipboard@8.1.3@ngx-clipboard/src/clipboard.directive.ts is not part of the compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

### ISSUE THREAD

**Issue by jendy2012** [maxisam/ngx-clipboard#97]
<img width="1168" alt="wx20171216-163414 2x" src="https://user-images.githubusercontent.com/2418263/34068900-8adef1fe-e27f-11e7-9778-cb5ad8c4a7ef.png">

**Comment by tfiwm** [comment]
It's clipboard version 9.0.0 -> you can see it the screenshot ;)
and is related to the same problem like in #100

**Comment by maxisam** [comment]
close this one and track it in #100
