### ISSUE TITLE
Linting error on clipboard.directive.ts

### ISSUE THREAD

**Issue by rich-saul** [maxisam/ngx-clipboard#98]
When I use ngx-clipboard it works without issue.  Very nice!  But when I'm linting, testing, and packing my product for Production, TSLint complains about ngx-clipboard:

.../node_modules/ngx-clipboard/src/clipboard.directive.ts[10, 5]: In the class "ClipboardDirective", the directive input property "targetElm" should not be renamed.Please, consider the following use "@Input() targetElm: string"

I can eliminate the error by setting "no-input-rename" to false in my tslint.json file, but this disables this check for my entire project.

I'm using ngx-clipboard@9.0.0.

**Comment by maxisam** [comment]
You can disable linting on 3rd party package. 
Thx

**Comment by rich-saul** [comment]
@maxisam I could not see how to disable linting on 3rd party packages in TSLint.  Do you know what option to invoke to do this?

**Comment by maxisam** [comment]
Google skipLibCheck

**Comment by rich-saul** [comment]
Thanks.  I'll check it out.
